### ISSUE TITLE
Can't create a meeting with invitation.

### ISSUE THREAD

**Issue by Ole01** [Ericsson/exchangecalendar#170] opened 2015-04-27 11:15 UTC
Hi all,

I'm running latest TB-31.6 with latest Lightning 3.3.3 and Exchange EWS in version 3.3.2~rc1 on win8.1 system.
To create a meeting without invitation, works fine. But when I add a new meeting with invitation to an exchange calendar, then I get the error message: "An error occurred when writing to the calendar ...!" Error code: MODIFICATION_FAILED
Then the calendar for about 1min is in the write-only mode.
The error occurs with all versions from 3.3.0 to 3.3.2 RC1. 
With version 3.2.0 Beta77 (1st-setup), the error did not occur.

The setup is:
	Windows 8.1
	Thunderbird 31.6.0
	Lightning 3.3.3
	Exchange EWS provider v3.3.2 RC1 (also tested with 33.0 to 3.3.2 RC1)

**Comment by Ole01** [comment] 2015-05-19 13:57
I have further tested. The error occurs if I invite people who have not shared their calendar.
If I enter the name or email address in the list of the invite attendees windows, the calendar change to non-writable status.
When I invite people who have shared their calendar with me, it works.
![Uploading error.jpg…]()

**Comment by Ole01** [comment] 2015-05-19 13:59
![error](https://cloud.githubusercontent.com/assets/12127058/7704637/f1b22cec-fe3f-11e4-91bf-f9ee6e4a80b9.jpg)

**Comment by isanchez** [comment] 2015-05-19 14:51
Same here, I can't assure if it works when someone share their calendar,
but I can't create an appointment and invite other people. If I create it
in OWA it works and Thunderbird syncs the appointment without problems.

My setup is:

Linux Mint 17.1 Rebecca
Thunderbird 31.7.0
Lightning 3.3.7
Exchange EWS Provider 3.3.2

**Comment by bavincen** [comment] 2015-06-04 06:04
This issue exists if a user not sharing his availability?

**Comment by Ole01** [comment] 2015-06-04 21:20
Yes. When I invite a user who has not shared his calendar with me, the calendar switches in the read-only mode.

**Comment by bavincen** [comment] 2015-06-11 11:40
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

yes 
please check this if any bug sould have got resolved

**Comment by Ole01** [comment] 2015-06-11 13:49
With 3.4 beta1 the invitation works fine, but the appointments do not appears in the calendar, see issue #216

**Comment by advancingu** [comment] 2015-07-24 15:25
I'm having the same issue as Ole01 describes [here](https://github.com/Ericsson/exchangecalendar/issues/170#issuecomment-109055183) with `exchangecalendar-3.4.0.beta5.xpi` and Lightning 3.3.3 on Thunderbird 31.8.0.
Is there a way to fix this behavior?

**Comment by cseader** [comment] 2015-08-25 04:25
Same with Beta 7. Anyone here have a fix yet on #216

**Comment by cseader** [comment] 2015-08-25 14:51
OK. So the winning match is using Thunderbird 38.2.0, Lightning version 4.0.0.1 and Exchange EWS Provider 3.4.0~beta7 . The one thing that made the difference is the Lightning version. If you change the Lightning version to 4.2.0 then your out of luck. Are we able to do tests with newer versions of Lightning?

**Comment by bavincen** [comment] 2015-08-25 15:19
We are not supporting greater than 4.0 lightning as of now.
yes testing can be done .

Sent from my Sprint phone.

----- Reply message -----

**Comment by cseader** [comment] 2015-08-25 16:04
Good to know. Thank You. The requirements to getting this working should be called out somewhere. Maybe they are and I just missed it. Thanks again.

**Comment by advancingu** [comment] 2015-08-26 09:47
@bavincen How is this not a bug? This ticket is about Lightning 3.3 and the feature of creating meetings with invitations is not working.

**Comment by bavincen** [comment] 2015-08-26 10:07
@advancingu please see the comments

**Comment by Ole01** [comment] 2015-08-26 10:28
@bavincen 
with TB 38.2.0, Lightning 4.0.2 and Exchange EWS Provider 3.4.0 beta 7 is the problem the same as described above.

**Comment by bavincen** [comment] 2015-08-26 10:35
@Ole01 I am using the same.. no issues. how to reproduce it please???

**Comment by Ole01** [comment] 2015-08-26 11:32
It's the same like described above. The error occurs if I invite people who have not shared their calendar. When I invite people who have shared their calendar with me, it works.
I have the error on two computers and my colleague has also the problem.
Maybe a problem with the localisation? I have the German interface. (general.useragent.locale = de)

**Comment by otichy** [comment] 2015-09-28 19:29
Same error here, TB 38.2.0, Lightning 4.0.2, EWS Provider 3.5.0-b0 (I updated today, when I noticed the behaviour, but I don't really remember from which version, to 3.4.0 rc1 and then to 3.5.0-b0). Same problem with all of them. I am on Sharepoint Online (Office365) and it worked fine until now. I tried unsubscribing/subscribing, but that did no good. I've also noticed that now I don't see free/busy info when I am inviting attendees. I am also able to create an appointment without inviting anyone and then adding the invitees, but they are not really added when I check via OWA. When added via OWA, both the appointment and the attendees are visible in TB.

**Comment by otichy** [comment] 2015-09-28 19:36
OK, i confirm <cseader commented on Aug 25> - downgraded to Lightning 4.0.0.1 and it works again. No idea if any of the versions between 4.0.0.1 and 4.0.2 work as well though.

**Comment by bavincen** [comment] 2015-09-29 06:00
please use the lightning stable version only

**Comment by Ole01** [comment] 2015-09-29 07:04
@bavincen The 4.0.2.1 version is the last stable version of lightning  
https://addons.mozilla.org/de/thunderbird/addon/lightning/

**Comment by otichy** [comment] 2015-09-29 23:29
@bavincen: I only use the version that installs through automatic updates - I had to turn the automatic updates off to keep the EWS working. I guess there should be at least warning about this somewhere.

**Comment by Ole01** [comment] 2015-09-30 09:14
The issue also exists with 3.4.0-rc2. and Windows10, TB 38.2.0, Lightning  4.0.2.1 (last stable)

@bavincen: Why is the issue closed?

**Comment by bavincen** [comment] 2015-09-30 11:25
Help us fixing it for windows?

**Comment by Ole01** [comment] 2015-09-30 11:32
Yes of course. Which infos do you need? Log-files? What should I try?

**Comment by bavincen** [comment] 2015-09-30 11:36
Yes please help us with bug-fixing if possible..

**Comment by otichy** [comment] 2015-09-30 12:41
I'd be happy to help as well, let me know what I need to do.

**Comment by bavincen** [comment] 2015-10-01 05:46
I’m closing this issue because we are not supporting lightning 4.0.2

we support till 4.0.1 thanks

**Comment by bavincen** [comment] 2015-10-01 05:46
@Ole01 Our next version will support  4.0.2

**Comment by bavincen** [comment] 2015-10-01 05:46
can u list the issues with 4.0.2 in new issues... Thanks

**Closed by bavincen** 2015-10-01 05:46 UTC

**Comment by Ole01** [comment] 2015-10-01 05:59
I have the same error in version 4.0.1 and a new issue would be a copy of my first post only with others version numbers. I don't understand how to create a new issue helps. All infos are in this thread.

**Comment by B-Digital** [comment] 2016-11-02 21:14
Still having this issue.

Ubuntu 16.04 LTS
Thunderbird 45.4.0
Lightning 4.7.4
Exchange EWS Provider 3.8

I know this is closed but I don't believe it was fixed. I set the logging to be Extended information and looked through them with no indication there was an issue.

**Comment by bavincen** [comment] 2016-11-12 12:54
@B-Digital  I tested it in my TB it worked. We have done no fixing for this. it worked with old version that time. I have suggested same.

Thanks

PS: Please provide me steps to produce the same bug in my system if you still think there is some issue.
I also recommend checking it with no other calendar add-ons like  google calendar
