### ISSUE TITLE
Tasks syncing in 3.4.0-RC1

### ISSUE THREAD

**Issue by roibuschtee** [Ericsson/exchangecalendar#336] opened 2015-09-11 08:06 UTC
If you add a new Task in an Exchange Kalender it is not displayed in the "Tasks"-tab until you manually clear the cache. The counter in settings -> folder settings counts one up if you add a new task but in the offline-caching settings it doesn't. Syncing the Kalender does not change anything.

Thunderbird 38.2.0, EWS 3.4.0-RC1

**Comment by bavincen** [comment] 2015-09-16 06:36
is that happening when calendar goes offline?

**Comment by chrislong** [comment] 2015-10-30 15:23
I have this issue, too. Clearing the cache fixes it. So does switching the calendar off and back on (not whether to display it, but in the Edit Calendar dialog).

Thunderbird 38.3.0, EWS 3.4.0

**Comment by bavincen** [comment] 2015-11-03 15:07
Are you having this issue til

**Comment by bavincen** [comment] 2015-11-03 15:08
Are you still having the issue

**Comment by poetimp** [comment] 2015-11-18 16:45
I am still having the issue. I can add tasks and they are added to exchange but they do not show up on the T-Bird task list until I manually sync. I have not tried clearing cache but resync'ing is a simple workaround. I am using 3.5.0-beta1

**Comment by adambro** [comment] 2015-11-25 12:39
Same for me using 3.5.0-beta1 version on Thunderbird 38.3.0 on Ubuntu 14.04.

**Comment by adambro** [comment] 2015-11-25 15:20
Attached log where I tried to add `XXXXX` task using input box below list of tasks.
[add_XXXXX_task_exchange_log.txt](https://github.com/Ericsson/exchangecalendar/files/43997/add_XXXXX_task_exchange_log.txt)

**Comment by jitseniesen** [comment] 2015-12-02 14:23
I have the same (or similar) issue: after adding a task it does not show up inside Thunderbird but it does show up if I look directly in Outlook. Resync-ing does not help for me, but clearing the cache does (right-click on calendar, "Exchange (EWS) Properties", "Offline cache" tab). 

The activity manager shows after adding a task:
* "Uni tasks": Received updates from EWS Server (New: 1, Changed: 0, Deleted: 0)
* Added task "test z" (Uni tasks)

The log (from menu Edit > Preferences > Exchange (EWS) > Logging) got these entries:
```
1st-setup:2015-11-3 14:19:9.823:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})
1st-setup:2015-11-3 14:19:9.825:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})
1st-setup:2015-11-3 14:19:9.825:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-11-3 14:19:10.92:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})
1st-setup:2015-11-3 14:19:10.93:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})
1st-setup:2015-11-3 14:19:10.93:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-11-3 14:19:10.275:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})
1st-setup:2015-11-3 14:19:10.276:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})
1st-setup:2015-11-3 14:19:10.277:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
```

Versions: Thunderbird 38.3.0, Lightning 4.0.4.1, Exchange EWS Provider 3.5.0-beta1

**Comment by dmrzzz** [comment] 2015-12-05 00:15
Same problem.  3.5.0-beta1, Thunderbird 38.4.0, Linux Mint 17.2.  I'll add that the problem occurs both when creating a new Task from within Thunderbird, and also when creating a new Task from outside Thunderbird (i.e. directly in Outlook Web Access); in either case, Thunderbird doesn't see the new task until I clear cache, or disable/re-enable the calendar, or quit and restart Thunderbird.

**Comment by adambro** [comment] 2015-12-30 11:35
Same for 3.5.0 release with Thunderbird 38.4.0 and Lightning 4.0.4.1

Seems to be a duplicate of #295

**Comment by bavincen** [comment] 2015-12-30 15:11
We wi fix this in next release..

**Comment by bavincen** [comment] 2016-01-30 06:38
is this issue happening in latest addon

**Comment by adambro** [comment] 2016-02-01 08:30
I can confirm it is still present in in 3.5.0 release, as I mentioned 2 comments above :) Is there anything I could do to make resolving the bug easier?

**Comment by jitseniesen** [comment] 2016-02-14 13:37
Just to confirm the issue is still present in 3.6.0-beta1. @bavincen is there a specific commit which you thought would fix this?

I found out that if you add a task (which does not show) and then change the option for "Show" in the left column, e.g. to "Incomplete tasks" or "All", this triggers a refresh after which newly added tasks are shown.

**Comment by stephanmehlhase** [comment] 2016-03-17 15:41
I am having similar issues with the task synchronization. I configured a "calendar" to point to the tasks folder on the exchange server. If I add a task now in Thunderbird, it gets created on the server (i.e. I see it in Outlook), but Thunderbird doesn't show it. To be exact, Thunderbird does not show any tasks neither those created with Thunderbird nor those on the server. In the EWS folder properties I see the correct number of Tasks. If I change a task in Outlook, I see later that the plugin reports one changed item for that calendar. However, it won't show any task at all.

**Comment by dmrzzz** [comment] 2016-07-26 18:34
Never saw a resolution comment here, but FWIW I just upgraded from 3.5 to 3.8.0 and this seems to be working properly for me now.

**Comment by bavincen** [comment] 2016-07-27 01:46
Fixed sorry for late response

**Comment by bavincen** [comment] 2016-07-27 03:42
https://github.com/Ericsson/exchangecalendar/commit/ab836f966aa9febb8dadff1196a2440426ee174b

**Closed by bavincen** 2016-07-27 03:42 UTC
Labels: bug

**Comment by bavincen** [comment] 2016-07-27 03:44
Sorry here is the correct commit

https://github.com/Ericsson/exchangecalendar/commit/5db3c8d9abf6a780cf8abd4fb84f486c5195916d
