### ISSUE TITLE
after upgrade to v3.4.0-beta1 my mails are not displayed anymore

### ISSUE THREAD

**Issue by rjayasinghe** [Ericsson/exchangecalendar#211] opened 2015-06-11 07:24 UTC
Hi!

I an on icedoce 31.7.0 with iceowl 3.3.7 on Debian Jessie  Yesterday an upgrade of the Exchange EWS provider was proposed. I upgraded to v3.4.0-beta1 and afterwards Icedove failed to display the body of my emails. The calendar worked all fine, but mail was gone. After disabling or downgrading the plugin to EWS provider 3.3.2 everything worked fine again.

Best Regards,
Robin

**Comment by 127001** [comment] 2015-06-11 07:36
Same here, after the update, message body isn't shown anymore. Switching message view to simple html or plain text doesn't help.
Running Mac OSX 10.10.4 and Thunderbird 31.7.0
Disabling the plugin fixes the message viewing.

**Comment by ehrenfeu** [comment] 2015-06-11 07:46
This is a duplicate of #207.

**Comment by bavincen** [comment] 2015-06-11 08:20
We have fixed it already..please wait for next release. you can try installing latest too

https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

**Closed by bavincen** 2015-06-11 08:20 UTC
