### ISSUE TITLE
Reminder window is showing up multiple times

### ISSUE THREAD

**Issue by offlinehoster** [Ericsson/exchangecalendar#132] opened 2015-03-11 21:55 UTC
The reminder pop-up window for an appointment is showing up multiple times. And you can't click on "close all" you have to click on the x at the upper right corner.

Any ideas? I am running v3.3.1 RC5

Cheers
Christian

**Comment by bavincen** [comment] 2015-03-12 03:41
Hello @Sarazin
Reminders has to bee dismissed which means you are supposed to click dismiss or dismiss all button

Unless dismissed popup will appear

Thanks 

-----Original Message-----

**Comment by offlinehoster** [comment] 2015-03-12 08:10
Hi @bavincen 

i can't click on dismis (all).

Nothing happen if i click on that button. I have to click on the x in the upper right corner.

**Comment by bavincen** [comment] 2015-03-12 08:24
Can you please use our recent release .
:)

-----Original Message-----

**Comment by offlinehoster** [comment] 2015-03-12 08:30
Which one (version) do you mean?

**Comment by bavincen** [comment] 2015-03-12 09:47
https://github.com/Ericsson/exchangecalendar/releases

RC5

**Comment by offlinehoster** [comment] 2015-03-12 09:49
Hi @bavincen 

did YOU read what i was writing at the beginning of this issue?

---> Any ideas? I am running v3.3.1 RC5

Cheers
Christian

**Comment by bavincen** [comment] 2015-03-12 09:53
ooh!
we would like a screenshot.
please tell us your thundebird version,operating system,

**Comment by offlinehoster** [comment] 2015-03-12 09:59
;)

Thunderbird 31.5.0 and Lightning 3.3.3

At the moment i don't see any Reminder Windows, it might be hard to show you a screenshot, i mean, how should i show you that clicking is not working ;)

If this does not appear in RC6 or the version after RC5 i will close this issue.

**Comment by bavincen** [comment] 2015-03-12 10:05
I guess the issue is not with reminder , there is one known issue. If your queue jobs(pending updates)  are higher when you click dismiss ( button goes disabled?)  for the first time, you have to wait till response. ( if you are having huge number of events its possible )

**Comment by Mechtilde** [comment] 2015-03-12 12:51
Sometimes I also have this problem. But IMO this is not (directly) a
problem of this extension.

I identify the missing connection as the problem.

Look at the preferences of your EWS Calender whether you have writable
connection to the server.

So I summarize there is a Problem with the reminder but only if there is
no connection to the server.

My Idea: Is it possible to cache this information (closing the reminder)
until getting a usable connection to the EWS server.

Am 12.03.2015 um 11:05 schrieb bavincen:
> I guess the issue is not with reminder , there is one known issue. If your queue jobs(pending updates)  are higher when you click dismiss ( button goes disabled?)  for the first time, you have to wait till response. ( if you are having huge number of events its possible )
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Ericsson/exchangecalendar/issues/132#issuecomment-78452452
> 

-- 
Mechtilde Stehmann

## PGP encryption welcome
## Key-ID 0x141AAD7F

**Comment by bavincen** [comment] 2015-03-13 04:39
@Mechtilde we are planning the same,  it may be a larger work..

**Comment by bavincen** [comment] 2015-03-13 05:41
Let me know if that event still in ur calendar, 
what you need to do is,
click dismiss or dismiss all 
then 
check that event deleted from thundebird,
then after restart it appears..
:)

**Comment by bavincen** [comment] 2015-03-13 05:44
This is not problem related to event, this make any event fail :)

Ok, how it happens
start thunderbird without internet without connection with Cache enabled only
then connect to internet, do your update, any update you are doing to any event will fail,

Reason:it unable to amintain the integrity as the first sync during thunderbird start up failed  ,because started without internet :)

**Closed** 2015-03-19 11:28 UTC
