### ISSUE TITLE
new events don't show up in calendar

### ISSUE THREAD

**Issue by andrewperrin** [Ericsson/exchangecalendar#216] opened 2015-06-11 13:03 UTC
Using EWS provider 3.4.0beta1, but the same behavior persists after reverting to 3.3.2. Thunderbird 38.0.1, Linux 64 bit, Lightning 4.0.0.1.

When creating a new appointment in the calendar, the new appointment does not show up in the Exchange calendar. Steps to reproduce:
1.) Create a new event in the calendar (for the example below, an all-day event, June 11, 2015, "Foo Bar Baz")
2.) No event is shown in the calendar.
3.) The event *does* show up in the calendar when using Outlook Web Services to view.
4.) Clicking Synchronize does *not* cause the event to show up.
5.) Usually, but not always, quitting Thunderbird and restarting it causes the event to show up.

Log files:
1.) Create a new event in the calendar:
`1st-setup:2015-5-4 8:48:14.618:[UNC] addItem id=null, aItem.calendar:[xpconnect wrapped (nsISupports, mivExchangeCalendar, calICalendarACLManager, calICalendar, calICalendarProvider, calIFreeBusyService, calIItipTransport, calISchedulingSupport, calICalendarProvider, nsIClassInfo)] (_addItem in mivExchangeCalendar.js:885)
1st-setup:2015-5-4 8:48:14.621:[UNC] adoptItem() (_adoptItem in mivExchangeCalendar.js:986)
1st-setup:2015-5-4 8:48:14.624:[UNC] adoptItem 2 Copy/pasted item. item.id:null (_adoptItem in mivExchangeCalendar.js:1025)
1st-setup:2015-5-4 8:48:14.631:[UNC] We have '0' alarms. (_convertCalAppointmentToExchangeAppointment in mivExchangeCalendar.js:4747)
1st-setup:2015-5-4 8:48:14.634:[UNC] convertCalAppointmentToExchangeAppointment: Item is not an invitation.
 (_convertCalAppointmentToExchangeAppointment in mivExchangeCalendar.js:4836)
1st-setup:2015-5-4 8:48:14.637:[UNC] makeRecurrenceRule: We have no recurrenceInfo (_makeRecurrenceRule in mivExchangeCalendar.js:4218)
1st-setup:2015-5-4 8:48:14.640:[UNC] getEWSTimeZoneId:America/New_York (_getEWSTimeZoneId in mivExchangeCalendar.js:8436)
1st-setup:2015-5-4 8:48:14.647:[UNC] getEWSTimeZoneId:America/New_York (_getEWSTimeZoneId in mivExchangeCalendar.js:8436)
1st-setup:2015-5-4 8:48:14.653:[UNC] convertCalAppointmentToExchangeAppointment: <nsTypes:CalendarItem xmlns:nsTypes="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:nsMessages="http://schemas.microsoft.com/exchange/services/2006/messages"><nsTypes:Subject>Foo Bar Baz</nsTypes:Subject><nsTypes:Sensitivity>Normal</nsTypes:Sensitivity><nsTypes:Body BodyType="HTML">&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;&lt;/head&gt;&lt;body&gt;&lt;/body&gt;&lt;/html&gt;</nsTypes:Body><nsTypes:Categories/><nsTypes:Importance>Normal</nsTypes:Importance><nsTypes:ReminderIsSet>false</nsTypes:ReminderIsSet><nsTypes:Start>2015-06-11T04:00:00Z</nsTypes:Start><nsTypes:End>2015-06-12T03:59:00Z</nsTypes:End><nsTypes:IsAllDayEvent>true</nsTypes:IsAllDayEvent><nsTypes:LegacyFreeBusyStatus>Free</nsTypes:LegacyFreeBusyStatus><nsTypes:Location/><nsTypes:StartTimeZone Id="Eastern Standard Time"/><nsTypes:EndTimeZone Id="Eastern Standard Time"/></nsTypes:CalendarItem> (_convertCalAppointmentToExchangeAppointment in mivExchangeCalendar.js:4946)
1st-setup:2015-5-4 8:48:14.741:c914c67e-1c90-48a0-a824-f4aac1e15acf: : 1 ExchangeRequest.sendRequest : user=AD\aperrin, url=https://outlook.unc.edu/EWS/Exchange.asmx
1st-setup:2015-5-4 8:48:14.744:c914c67e-1c90-48a0-a824-f4aac1e15acf: We have a prePassword: *******
1st-setup:2015-5-4 8:48:14.746:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})
1st-setup:2015-5-4 8:48:14.749:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})
1st-setup:2015-5-4 8:48:14.752:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-5-4 8:48:14.754:c914c67e-1c90-48a0-a824-f4aac1e15acf: : ExchangeRequest.loadstart
1st-setup:2015-5-4 8:48:14.803:c914c67e-1c90-48a0-a824-f4aac1e15acf: : ExchangeRequest.progress. loaded:667, total:667
1st-setup:2015-5-4 8:48:14.805:c914c67e-1c90-48a0-a824-f4aac1e15acf: : ExchangeRequest.onLoad :load, readyState:4, status:200
1st-setup:2015-5-4 8:48:14.807:c914c67e-1c90-48a0-a824-f4aac1e15acf: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:200
1st-setup:2015-5-4 8:48:14.813:[UNC] createItemOk 1 (_createItemOk in mivExchangeCalendar.js:5178)
1st-setup:2015-5-4 8:48:14.815:[UNC] createItemOk We have no attachments to create. (_createItemOk in mivExchangeCalendar.js:5198)
1st-setup:2015-5-4 8:48:14.818:[UNC] setProperty. aName:currentStatus, aValue:0 (setProperty in mivExchangeCalendar.js:826)
1st-setup:2015-5-4 8:48:14.821:[UNC] setProperty. aName:exchangeCurrentStatus, aValue:0 (setProperty in mivExchangeCalendar.js:826)
1st-setup:2015-5-4 8:48:14.823:c914c67e-1c90-48a0-a824-f4aac1e15acf: : ExchangeRequest.loadend
1st-setup:2015-5-4 8:48:14.825:c914c67e-1c90-48a0-a824-f4aac1e15acf: : ExchangeRequest.loadend :loadend, readyState:4, status:200`

2.) Confirm event is not displayed on the calendar; confirm event is displayed in Outlook Web Services view of calendar
3.) Click synchronize:
`1st-setup:2015-5-4 8:50:42.630:[UNC] refresh (_refresh in mivExchangeCalendar.js:2837)
1st-setup:2015-5-4 8:50:42.632:[UNC] weAreSyncing. So no refresh. (_refresh in mivExchangeCalendar.js:2845)
1st-setup:2015-5-4 8:50:42.634:[UNC] getItems 0:   aItemFilter, 65542  aCount, 0 aRangeStart,  1970/01/01 00:00:00 UTC isDate=0 nativeTime=0 aRangeEnd, 2015/06/12 00:00:00 America/New_York isDate=1 nativeTime=1434081600000000 aListener , [xpconnect wrapped calIOperationListener] (_getItems in mivExchangeCalendar.js:2194)
1st-setup:2015-5-4 8:50:42.636:[UNC] getItems 2: aRangeStart:1970/01/01 00:00:00 UTC isDate=0 nativeTime=0 (_getItems in mivExchangeCalendar.js:2202)
1st-setup:2015-5-4 8:50:42.638:[UNC] getItems 3: aRangeEnd:2015/06/12 00:00:00 America/New_York isDate=1 nativeTime=1434081600000000 (_getItems in mivExchangeCalendar.js:2210)
1st-setup:2015-5-4 8:50:42.640:[UNC] Tasks are requested by calendar. (_getItems in mivExchangeCalendar.js:2247)
1st-setup:2015-5-4 8:50:42.642:[UNC] This folder is not able to support requested items. this.OnlyShowAvailability:false (_getItems in mivExchangeCalendar.js:2374)
1st-setup:2015-5-4 8:50:42.644:[UNC] setProperty. aName:currentStatus, aValue:0 (setProperty in mivExchangeCalendar.js:826)
1st-setup:2015-5-4 8:50:42.646:[UNC] getItems 0:   aItemFilter, 7  aCount, 0 aRangeStart,  null aRangeEnd, null aListener , [xpconnect wrapped calIOperationListener] (_getItems in mivExchangeCalendar.js:2194)
1st-setup:2015-5-4 8:50:42.648:[UNC] getItems 2: aRangeStart:null (_getItems in mivExchangeCalendar.js:2206)
1st-setup:2015-5-4 8:50:42.650:[UNC] getItems 3: aRangeEnd:null (_getItems in mivExchangeCalendar.js:2214)
1st-setup:2015-5-4 8:50:42.652:[UNC] Tasks are requested by calendar. (_getItems in mivExchangeCalendar.js:2247)
1st-setup:2015-5-4 8:50:42.653:[UNC] This folder is not able to support requested items. this.OnlyShowAvailability:false (_getItems in mivExchangeCalendar.js:2374)
1st-setup:2015-5-4 8:50:42.656:[UNC] setProperty. aName:currentStatus, aValue:0 (setProperty in mivExchangeCalendar.js:826)
1st-setup:2015-5-4 8:50:42.711:[UNC] getItems 0:   aItemFilter, 65546  aCount, 0 aRangeStart,  2015/06/07 00:00:00 America/New_York isDate=1 nativeTime=1433649600000000 aRangeEnd, 2015/06/14 00:00:00 America/New_York isDate=1 nativeTime=1434254400000000 aListener , [xpconnect wrapped calIOperationListener] (_getItems in mivExchangeCalendar.js:2194)
1st-setup:2015-5-4 8:50:42.713:[UNC] getItems 2: aRangeStart:2015/06/07 00:00:00 America/New_York isDate=1 nativeTime=1433649600000000 (_getItems in mivExchangeCalendar.js:2202)
1st-setup:2015-5-4 8:50:42.715:[UNC] getItems 3: aRangeEnd:2015/06/14 00:00:00 America/New_York isDate=1 nativeTime=1434254400000000 (_getItems in mivExchangeCalendar.js:2210)
1st-setup:2015-5-4 8:50:42.717:[UNC] Events are requested by calendar. (_getItems in mivExchangeCalendar.js:2246)
1st-setup:2015-5-4 8:50:42.718:[UNC] Events are requested and this is possible for this folder (_getItems in mivExchangeCalendar.js:2381)
1st-setup:2015-5-4 8:50:42.720:[UNC] getItems 5a: aRangeStart:2015/06/07 00:00:00 America/New_York isDate=1 nativeTime=1433649600000000 (_getItems in mivExchangeCalendar.js:2474)
1st-setup:2015-5-4 8:50:42.722:[UNC] getItems 5b: aRangeEnd:2015/06/14 00:00:00 America/New_York isDate=1 nativeTime=1434254400000000 (_getItems in mivExchangeCalendar.js:2475)
1st-setup:2015-5-4 8:50:42.724:[UNC] getItemsFromMemoryCache startDate:2015/06/07 00:00:00 America/New_York isDate=1 nativeTime=1433649600000000, endDate:2015/06/14 00:00:00 America/New_York isDate=1 nativeTime=1434254400000000, aListener:[xpconnect wrapped calIOperationListener], aExporting:false (_getItemsFromMemoryCache in mivExchangeCalendar.js:2638)
1st-setup:2015-5-4 8:50:42.727:[UNC] We got '44' events and  '0'  tasks from memory cache. (_getItemsFromMemoryCache in mivExchangeCalendar.js:2702)
1st-setup:2015-5-4 8:50:42.729:[UNC] We have a listener so going to inform it.(2) (_getItemsFromMemoryCache in mivExchangeCalendar.js:2704)
1st-setup:2015-5-4 8:50:42.824:[UNC] setProperty. aName:currentStatus, aValue:0 (setProperty in mivExchangeCalendar.js:826)
1st-setup:2015-5-4 8:50:42.826:[UNC] No dateChanged. Not going to request items from server. (_getItems in mivExchangeCalendar.js:2565)
1st-setup:2015-5-4 8:50:42.831:[UNC] getItems 0:   aItemFilter, 65544  aCount, 0 aRangeStart,  2015/06/11 08:46:55 America/New_York isDate=0 nativeTime=1434026815000000 aRangeEnd, 2015/06/12 00:00:00 America/New_York isDate=1 nativeTime=1434081600000000 aListener , [xpconnect wrapped calIOperationListener] (_getItems in mivExchangeCalendar.js:2194)
1st-setup:2015-5-4 8:50:42.833:[UNC] getItems 2: aRangeStart:2015/06/11 08:46:55 America/New_York isDate=0 nativeTime=1434026815000000 (_getItems in mivExchangeCalendar.js:2202)
1st-setup:2015-5-4 8:50:42.835:[UNC] getItems 3: aRangeEnd:2015/06/12 00:00:00 America/New_York isDate=1 nativeTime=1434081600000000 (_getItems in mivExchangeCalendar.js:2210)
1st-setup:2015-5-4 8:50:42.837:[UNC] Events are requested by calendar. (_getItems in mivExchangeCalendar.js:2246)
1st-setup:2015-5-4 8:50:42.839:[UNC] Events are requested and this is possible for this folder (_getItems in mivExchangeCalendar.js:2381)
1st-setup:2015-5-4 8:50:42.841:[UNC] getItems 5a: aRangeStart:2015/06/11 08:46:55 America/New_York isDate=0 nativeTime=1434026815000000 (_getItems in mivExchangeCalendar.js:2474)
1st-setup:2015-5-4 8:50:42.843:[UNC] getItems 5b: aRangeEnd:2015/06/12 00:00:00 America/New_York isDate=1 nativeTime=1434081600000000 (_getItems in mivExchangeCalendar.js:2475)
1st-setup:2015-5-4 8:50:42.845:[UNC] getItemsFromMemoryCache startDate:2015/06/11 08:46:55 America/New_York isDate=0 nativeTime=1434026815000000, endDate:2015/06/12 00:00:00 America/New_York isDate=1 nativeTime=1434081600000000, aListener:[xpconnect wrapped calIOperationListener], aExporting:false (_getItemsFromMemoryCache in mivExchangeCalendar.js:2638)
1st-setup:2015-5-4 8:50:42.848:[UNC] We got '25' events and  '0'  tasks from memory cache. (_getItemsFromMemoryCache in mivExchangeCalendar.js:2702)
1st-setup:2015-5-4 8:50:42.850:[UNC] We have a listener so going to inform it.(2) (_getItemsFromMemoryCache in mivExchangeCalendar.js:2704)
1st-setup:2015-5-4 8:50:42.894:[UNC] setProperty. aName:currentStatus, aValue:0 (setProperty in mivExchangeCalendar.js:826)
1st-setup:2015-5-4 8:50:42.896:[UNC] No dateChanged. Not going to request items from server. (_getItems in mivExchangeCalendar.js:2565)
1st-setup:2015-5-4 8:50:43.944:[UNC] refresh (_refresh in mivExchangeCalendar.js:2837)
1st-setup:2015-5-4 8:50:43.946:[UNC] weAreSyncing. So no refresh. (_refresh in mivExchangeCalendar.js:2845)`

**Comment by Ole01** [comment] 2015-06-11 13:39
Same here. Using EWS provider 3.4.0beta1, Thunderbird 31.7.0, Lightning 3.3.3.,Windows 8.1.
After reverting to 3.3.2 and delete and recreate the calendar the appointments appear again.

**Comment by bavincen** [comment] 2015-06-12 05:44
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
please use this latest version and let us know if that bug still there

Goto EWS settings -> offline cache-->clear cache wait for syncing restart ,,

**Comment by Ole01** [comment] 2015-06-12 06:14
I have installed the latest version (https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon) but the bug is still there.

**Comment by bavincen** [comment] 2015-06-12 06:43
Goto EWS settings -> offline cache-->clear cache wait for syncing restart ,,  please try this

**Comment by Ole01** [comment] 2015-06-12 06:58
I did that and then all appointments are appeared. But a new event does not appear till I clear the offline-cache again.

**Comment by brenboy** [comment] 2015-06-13 09:12
I see the same issue too with Thunderbird 38.0.1, Lightning 4.0.0.1 and Exchange Calendar addon 3.4.2b2. 

I also still see the issues I reported in #122 and #175. Something was really broken in 3.3.1RC3 and has not been fixed even though the reported issues are just closed by the developers without confirmation of a fix from the users reporting the issues.

Having to clear the cache every time an invite is accepted, deleted or added is not a viable workaround.

**Comment by bavincen** [comment] 2015-06-13 10:37
We closed it found duplicate. Or we checked it fixed.

**Comment by bavincen** [comment] 2015-06-13 11:29
Is that new updates on old events happening?
When you take any action accept or decline , does that new event appears?

**Comment by Ole01** [comment] 2015-06-13 11:48
No, accept or decline an old event do not help. Only if I clear the offline-cache, the events appear.

**Comment by andrewperrin** [comment] 2015-06-13 11:49
Unfortunately the relevant computer is in my office so I can't check 
until Monday. I will respond then. Thank you for your work!

**Comment by brenboy** [comment] 2015-06-13 11:58
This happens for accept new events, update old events, delete old events and create new events. The lightning calendar just does not update

**Comment by bavincen** [comment] 2015-06-13 16:01
hello all, i tried to reproduce the issue. unfortunately the same not happening 
what i did , was 
created a event where i added one invitee sent that.
edited it in owa and checked.

received new event ( i am not pressing any sync button)
organized edited it sent an update with chnaged time it worked.

so do i miss something

**Comment by bavincen** [comment] 2015-06-13 16:14
![capture](https://cloud.githubusercontent.com/assets/8401561/8145025/f28b7072-1214-11e5-8811-7336c479629a.JPG)
if you have option disabled in OWA ,new events will not appear in calendar, once u accept/tentate then it comes to local calendar

**Comment by bavincen** [comment] 2015-06-13 16:22
@brenboy l,ooks like you are completely disconnected from exchange sever

**Comment by brenboy** [comment] 2015-06-14 00:12
Hi Bavincen,

I enabled the automatic processing option and it made no difference. Accept, create and delete of events in Lightning do not change unless I clear the cache or restart Thunderbird.

I'm not disconnected from the Exchange server because when I accept, create and delete, everything is updated correctly in OWA (i.e. accepted and created invites are there and deleted invites are removed)

**Comment by bavincen** [comment] 2015-06-14 02:13
Can you grep syncFolderItemsOK and check number of items received for updation..
Just to cofirm calendar refresh is work.
Also can you check calendar refresh time..

Otherwuse delete the calendar and create it agin

**Comment by brenboy** [comment] 2015-06-14 06:00
I deleted my calendar and the sqlite files in my Thunderbird user profile directory.

Create new calendar:

1st-setup:2015-5-0 15:43:4.58:[Work] syncFolderItemsOK: Folderbase: calendar, Creation:0, Updates:0, Deletions:0, syncState: <snip>

Create new invite in Lightning calendar (new invite does not appear in Lightning Calendar but appears immediately in OWA):

1st-setup:2015-5-0 15:44:4.41:[Work] syncFolderItemsOK: Folderbase: calendar, Creation:1, Updates:0, Deletions:0, syncState:<snip>

Delete existing invite from Lightning calendar (existing invite not removed from Lightning Calendar but removed immediately in OWA):
1st-setup:2015-5-0 15:57:38.278:[Work] syncFolderItemsOK: Folderbase: calendar, Creation:0, Updates:0, Deletions:0, syncState:<snip>
1st-setup:2015-5-0 15:58:38.495:[Work] syncFolderItemsOK: Folderbase: calendar, Creation:0, Updates:0, Deletions:1, syncState:<snip>

Accept new invite from work colleague - no syncFolderItemsOK output

Clear exchange cache:

1st-setup:2015-5-0 15:54:52.35:[Work] syncFolderItemsOK: Folderbase: calendar, Creation:0, Updates:0, Deletions:0, syncState:<snip>

1st-setup:2015-5-0 15:54:52.49:[Work] First sync is done. Normal operation is starting. (_syncFolderItemsOK in mivExchangeCalendar.js:8062)
1st-setup:2015-5-0 15:54:52.304:[Work] First sync is done. Processed getItemsSyncQueue. (_syncFolderItemsOK in mivExchangeCalendar.js:8068)

**Comment by andrewperrin** [comment] 2015-06-15 16:29
I tried this morning with the master.zip and got the same behavior - new 
events (and new deletions) are not changed in the displayed calendar.

**Comment by andrewperrin** [comment] 2015-06-15 16:45
The problem does NOT exist using Thunderbird 31.6.0, Lightning 3.3.3, 
and EWS 3.3.2. I suspect, therefore, that it is a problem with the 
interaction between EWS and Lightning 4.

**Comment by Ole01** [comment] 2015-06-15 17:25
I have the problem with Lightning 3.3.3. See my first post.

**Comment by pluto00987** [comment] 2015-06-17 14:50
A 'me too':

I do not have the issue using Thunderbird 31.7.0 + Lightning 3.3.3 + EWS provider 3.3.2. I started having the issue after upgrading to Thunderbird 38.0.1 + Lightning 4.0.1.

I was able to downgraded back to Thunderbird 31.7.0 + Lightning 3.3.3 and the problem went away. No other changes. Still using EWS provider 3.3.2.

**Comment by bavincen** [comment] 2015-06-18 05:26
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

please check latest guys..need your updates

**Comment by bavincen** [comment] 2015-06-18 05:28
Please post your lightning Thunderbird version with reply

Thanks

**Comment by Ole01** [comment] 2015-06-18 06:26
It is the same problem with the new version. 
What have I done: update -> clear offline-cache -> new event 
I have tested Thunderbird 31.7.0 and Lightning 3.3.3. and then update to version 38.0.1/4.0.0.1.
The same problem in both versions.

And I have still a other problem with the new version. I'm from Germany and in my configuration the entry "general.useragent.local" is "de". With this value I get a error if I choose the EWS-Configuration of the calendar. 
Error message:
> XML-Verarbeitungsfehler: Nicht definierte Entität
> Adresse: chrome://exchangecalendar/content/exchangeSettings.xul
> Zeile Nr. 48, Spalte 1:<dialog xmlns="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"
> ^ 

This error don't appear with the value "en-US" in the entry "general.useragent.local"

**Comment by bavincen** [comment] 2015-06-18 09:20
if you are using 4.0 lightning, support is enabled now.. please confirm .. thanks

**Comment by andrewperrin** [comment] 2015-06-18 15:31
Confirming: I installed the latest using the online instructions at 
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon 
and am using Lightning 4.0.0.1, Thunderbird 38.0.1 for Linux 64bit. With 
this morning's version (downladed 11:24 am Eastern Time USA), the 
problem is fixed.

Thank you!

Andy Perrin

**Comment by bavincen** [comment] 2015-06-18 15:33
closing it

**Comment by brenboy** [comment] 2015-06-19 00:36
I won't able to test for a couple weeks

**Comment by brenboy** [comment] 2015-06-29 02:59
All,
I have tested 3.4 beta 4 and all 3 issues are now fixed (accept, create, delete).
Thanks for the good work!!
 


     On Friday, 19 June 2015, 10:33, Bren Mifsud <brenboy78@yahoo.com.au> wrote:
   

 
| I won't able to test for a couple weeks
 
|  From:"bavincen" <notifications@github.com>
Date:Thu, 18 Jun, 2015 at 11:33 AM
Subject:Re: [exchangecalendar] new events don't show up in calendar (#216)

 Closed #216.—
Reply to this email directly or view it on GitHub.    |

 |

**Comment by brenboy** [comment] 2015-06-29 03:26
I think this can remain closed. All of my issues are fixed by 3.4 beta 4

**Closed** 2015-06-29 04:18 UTC
Labels: bug
