### ISSUE TITLE
After any changes in events, calendar not refreshing

### ISSUE THREAD

**Issue by grigkar** [Ericsson/exchangecalendar#175] opened 2015-05-07 13:02 UTC
Hi there,
When I trying to add/delete/edit event in calendar, changes not appeared in calendar, but successful have sent to server. Manual sync is not worked, cache mode is not selected.
There is only one way to see changes - it's restarting thunderbird.

**Comment by brenboy** [comment] 2015-05-08 13:46
This sounds exactly like the issue I reported earlier:

https://github.com/Ericsson/exchangecalendar/issues/122

Manual sync doesn't work as you said but entering the "Exchange (EWS) Properties" option for your calendar and clicking Save refreshes the calendar and the added/deleted/edited events finally appear.

**Comment by grigkar** [comment] 2015-05-10 06:20
Hi, yes its the same issue. Do you know how to solve it?

**Comment by brenboy** [comment] 2015-05-10 06:24
No idea how to solve it. I suspect it is a bug 
 


     On Sunday, 10 May 2015, 16:20, grigkar <notifications@github.com> wrote:
   

 Hi, yes its the same issue. Do you know how to solve it?

**Comment by tfft** [comment] 2015-05-10 10:58
Yup, as noted in #122, this happen VERY often which requires me to restart TB at least 3-4 days per day which is a serious nuisance.

**Comment by muthusuba** [comment] 2015-05-29 07:47
Would you guys be able to check if https://github.com/Ericsson/exchangecalendar/tree/cacheandperformancefix fixes the problem, please?

**Comment by brenboy** [comment] 2015-05-29 08:41
Do we need to build the test image or can we just rename the cacheandperformancefix.zip file with an .xpi extension?




On Friday, 29 May 2015, 17:47, Muthu Subramanian <notifications@github.com> wrote:
 


Would you guys be able to check if https://github.com/Ericsson/exchangecalendar/tree/cacheandperformancefix fixes the problem, please?

**Comment by bavincen** [comment] 2015-05-29 08:50
yes you can rename and use it

**Comment by brenboy** [comment] 2015-05-29 08:59
I'm downloading this zip and renaming .zip to .xpi but Thunderbird reports that the add-on is corrupt and won't install it:
https://github.com/Ericsson/exchangecalendar/archive/cacheandperformancefix.zip
 


     On Friday, 29 May 2015, 18:50, bavincen <notifications@github.com> wrote:
   

 yes you can rename and use it—

**Comment by bavincen** [comment] 2015-05-29 09:01
please refer wiki page

 You have to zip files/folders of extracted/dowloaded zip file...

**Comment by brenboy** [comment] 2015-05-29 09:16
I followed the wiki and it installs successfully (looks to be based of 3.4.0 Beta 1)- thanks for the tip. 

I'll test the fix out over the coming week. 

For some reason I've seen a few timezone change messages appear after install similar to https://github.com/Ericsson/exchangecalendar/issues/194
 


     On Friday, 29 May 2015, 19:01, bavincen <notifications@github.com> wrote:
   

 please refer wiki pageYou have to zip files/folders of extracted/dowloaded zip file...—

**Comment by bavincen** [comment] 2015-05-29 09:21
always use latest :)

**Comment by brenboy** [comment] 2015-05-29 09:34
Is there a newer image that I should be trying?

I've done a couple of quick tests using the cacheandperformancefix.zip image and it looks like the problem still exists:

1) I tried to delete an invite from my Lightning calendar (right click - Delete Event) - invite removed from Lightning on the second deletion attempt but invite not removed from OWA so when Thunderbird restarts deleted event reappears in Lightning

2) I tried to create an invite from my Lightning calendar - new invite does not appear in Lightning but invite is visible in OWA. 'Synchronise Calendar' button has no effect.

**Comment by bavincen** [comment] 2015-05-29 09:37
nothing new
just follow the steps:

follow the installation steps again. ( i mean use latest til now)
right click on that calendar, select ews properties
in the folder properties tab you can find clear cache, wait for calendar to sync items from server. then you can check issue is exist or not

**Comment by brenboy** [comment] 2015-05-29 09:39
I'm not using caching. exchange-cache is disabled.

**Comment by brenboy** [comment] 2015-06-01 23:50
I've been using the cacheandperformancefix build that forces the exchange-cache on but the problem still exists i.e. updated meetings are not updated in Lightning whilst they are in OWA, deleting meetings in Lightning does not work and new meetings created in Lightning to do not get added to Lightning but they appear in OWA

**Comment by bavincen** [comment] 2015-06-02 05:42
can i clear cache, you have to go to ews properties for that..
if that is also failing delete and create your calendars 

thanks

**Comment by bavincen** [comment] 2015-06-04 06:19
Close this issue if fixed... l
working for us..
p.s:  checkout  `cacheandperformancefix` for latest work

**Comment by brenboy** [comment] 2015-06-04 07:24
I have just deleted my calendar, uninstalled Lightning and uninstalled this Exchange Calendar addon and deleted all sqlite and tmp files in my Thunderbird profile directory. I reinstalled Lightning 4.0b3, the latest cacheandperformancefix build and recreated my calendar.

Unfortunately I still see exactly the same issues with the latest cacheandperformancefix build. Those problems are: updated meetings are not updated in Lightning but they are updated in OWA, deleting meetings in Lightning does not work and new meetings created in Lightning to do not get added to Lightning but get added to OWA.

Are there any logs I can turn on to send you to help debug this and get to the root cause faster?

**Comment by bavincen** [comment] 2015-06-11 11:14
Please use our latest addon it is fixed..

**Comment by bavincen** [comment] 2015-06-11 11:14
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

**Closed** 2015-06-11 11:14 UTC
Labels: bug

**Comment by brenboy** [comment] 2015-06-11 12:39
Master branch or cacheandperformancefix branch?
