### ISSUE TITLE
Calendar stops syncing during  computer resume 

### ISSUE THREAD

**Issue by Mats1st** [Ericsson/exchangecalendar#126] opened 2015-03-03 18:17 UTC
Hi all,

I'm running latest TB-31.5 with latest Lightning 3.3.3 and Exchange EWS in version 3.3.1~rc1 on my win7 system. Every monday I have a repeating event in my companies outlook calendar. Sometimes it is impossible to close the notification popup by clicking the close button (only clicking on red cross works until the notification pops up again after a while). Why sometimes?: after restarting TB the notification pops up and can be managed by clicking on the close button (no new notification will pop up until next monday). 
Please do not hesitate to question for deeper information, if required.
Thanks in advance!

**Comment by Mechtilde** [comment] 2015-03-03 18:43
Please try Exchange EWS in version 3.3.1~rc4. It works for me under Linux.

Am 03.03.2015 um 19:17 schrieb Mats1st:

**Comment by Mats1st** [comment] 2015-03-03 20:15
I have installed current ~rc4 now, but I can feedback earliest on coming monday ...

**Comment by Mechtilde** [comment] 2015-03-05 09:42
I could figure out thi. It it takes a while to connect to the EWS server. In this time you can't close the reminder. After getting the connection to the EWS server it closes promptly.

**Comment by Mats1st** [comment] 2015-03-05 09:57
you are right! This is the behavior after restarting TB. It takes a while to connect and after a few seconds the dialog closes pomptly. But I close my TB very seldom (computer is mostly in energy save mode over night and will be restarted only twice a week maximum). So TB is also mostly not closed. And than it seems to have a problem to reconnect to the server! maybe you can investigate this like described above.

**Comment by bavincen** [comment] 2015-03-06 03:57
Hello
Sorry for inconvenience
First of all its not problem because of reminder
During resume (noticed sometimes) thunderbird calendar doesn't sync with ews server. We are investigating this..


Thanks

**Comment by sysadm-prs-de** [comment] 2015-03-14 10:21
Hello everyone,

this problem looks very familiar and has been reported in 2013 to 1st-setup.
The problem has been observed on MacOS X (all versions from 10.8.x upwards) - other OSs do not seem to show the same problem (tried Linux and Windows), BUT on MacOSX it is consistent!

Here is what happens:
Whenever TB is running while the machine goes into power save mode, one of my two calendars (both EWS 2010) goes into "read-only" and the task indicator reports 1 running & xy queued jobs.
Restarting TB doesn't change the behavior. Trying to uncheck the read-only flag doesn't help.
To salvage, one has to delete the entire calendar, restart TB and recreate the calendar.
After creating the calendar again, no tasks remain running.
At least one calendar has a lot of recurring events.

Even w/o letting the machine slip into power save, the calendar seems to "hang" after some time, or after starting TB the second or third time.
It doesn't seem to happen when there is only calendar. With two calendars, the "hang" alternates between the two.

Any ideas?
Thanks !

**Comment by enozkan** [comment] 2015-04-22 16:33
I am not sure if this is the same, but among my several Macs, my laptop (which goes to sleep regularly) tends to lose connectivity to my Exchange calendar after wake up. My solution is to restart Thunderbird (or to keep the laptop plugged, so that it won't go into sleep mode). This is true only for exchange calendars; Google or Zimbra calendars are fine, and my desktop Macs have no such issue. Happy to provide any logs if needed.

**Comment by sysadm-prs-de** [comment] 2015-04-22 16:36
Interesting - though in my case, restarting TB doesn't help at all...
However, it seem to have omething to do with the network layer, since sleeping definitely triggers the behavior AND if I have only one exchange calendar, I see the same behaviour, though a restart fixes the problem.
Once a second exchange cal is part of the calendar list, it cannot be salvaged...

**Comment by ehrenfeu** [comment] 2015-04-23 08:33
I can confirm this, after a suspend-resume cycle the connectivity is completely lost and can't be restored by explicitly asking for a calendar sync. The only thing that helps for me is to shut down Thunderbird and restart it.
BTW, I think it is the same when switching to offline mode and back to online later - from my feeling this is completely ignored by the Exchange Calendar (no problem with my regular CalDAV ones).

System is Ubuntu 14.10.

**Comment by muthusuba** [comment] 2015-05-29 08:09
I think, #195 is a duplicate of this...

**Comment by sysadm-prs-de** [comment] 2015-05-29 08:35
Yes, that looks very much like it...

On 29/05/15 10:09, Muthu Subramanian wrote:
>
> I think, #195 
> <https://github.com/Ericsson/exchangecalendar/issues/195> is a 
> duplicate of this...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Ericsson/exchangecalendar/issues/126#issuecomment-106737727>.
>

-- 
System Administrator                             mailto:sysadm@prs.de
Patzschke + Rasp Software GmbH                      http://www.prs.de
Bierstadter Straße 7                          Fax: +49-(0)611-1731-31
D-65189 Wiesbaden                            Phone: +49-(0)611-1731-0

Patzschke + Rasp Software GmbH, Bierstadter Str. 7, D-65189 Wiesbaden
Eintragung im Handelsregister: Amtsgericht Wiesbaden, HRB Nr. 22673
Geschäftsführer: Wolfgang Kechel, Till Immanuel Patzschke

**Comment by bavincen** [comment] 2015-06-04 06:01
Please use this branch if you are checking out "cacheandperformancefix" ,

https://github.com/Ericsson/exchangecalendar/tree/cacheandperformancefix

**Comment by bavincen** [comment] 2015-06-04 06:02
reopen if issue exists

**Closed by bavincen** 2015-06-04 06:02 UTC
Labels: bug

**Comment by Mats1st** [comment] 2015-06-05 20:12
Hello bavincen,

     As I can see - you and the team worked hard last two weeks. Do you 
create a 3.4.0beta1 including all implementations in the next days? I 
would be glad to test this new beta release!

Thanks in advance!
Regards,
Mats1st

Am 04.06.2015 um 08:01 schrieb bavincen:

**Comment by muthusuba** [comment] 2015-06-06 04:46
@Mats1st There are some small bugs still that probably require addressing, we will release it once those are cleared....
