### ISSUE TITLE
Job running endlessly prevents modifying calendar

### ISSUE THREAD

**Issue by senshu** [Ericsson/exchangecalendar#230] opened 2015-06-15 15:55 UTC
This issue is similar to what is explained in [this comment](https://github.com/Ericsson/exchangecalendar/issues/223#issuecomment-111979045) but I thought it deserved its own report.

While Thunderbird is running, at some point the status bar will show `1 running and N queued jobs`. The tooltip when hovering the status bar tells:
 ```
https://my-exchange-server/EWS/Exchange.asmx 1
MyExchangeCalendar N
```

From this point, the running job never stops. Each time I attempt to create or modify an event in the Exchange calendar, the number of queued jobs increases and the operation never completes.

The only workaround I could find was to close Thunderbird and open it again before making any change in the calendar.

I tried to look at the logs but I don't know where I can find them.

**Comment by bavincen** [comment] 2015-06-15 15:59
have you enabled tasks?

**Comment by OfficeDrone6000** [comment] 2015-06-15 17:27
Precise same thing happening here on 3.4.0b1 and b2.  Windows 7, Thunderbird 38.0.1, Lightning 4.0.0.1.  Problem does not happen with EWS 3.3.2, so I stepped down to that.  Am not sure what you mean by enabling tasks.

**Comment by bavincen** [comment] 2015-06-15 17:28
that means have you added calender for tasks :)

**Comment by OfficeDrone6000** [comment] 2015-06-15 17:32
Ah, got it -- in that case, no, I haven't enabled tasks.  Am happy to send logs if that would assist. 

Before the never-ending queued tasks would start under 3.4.0b1 and 2, I would get a system notification (in the Windows taskbar) that "system time zone set to lightning."  Bringing up the Windows time zone dialog would show that system remained set to EST.  The endless queue always started right after the mystery time zone "change."

**Comment by EricV2** [comment] 2015-06-15 19:00
FYI : I opened the very same bug and it has been closed as fixed. Nice to see this was just plain wrong.

**Comment by poetimp** [comment] 2015-06-15 19:38
I am experiencing the same thing as OfficeDrone6000 under Linux. I see the timezone message for a short period and then it goes away. The activity spinner then just spins indefinitely. I do have two calendars, one for events one for tasks. I have had it setup this way for years. Have things changed?

**Comment by bavincen** [comment] 2015-06-15 19:46
cool can you guys disable auto timezone in preference,
let us know if it works for you..
we have been working on beta issues, we have added lot of things, that makes the changes

**Comment by poetimp** [comment] 2015-06-15 19:59
I have turned off automatic timezone and things are looking much better. I will continue to watch and let you know if the problem resurfaces. For now, though, it is good. I appreciate the quick answer and all of the effort.

**Comment by OfficeDrone6000** [comment] 2015-06-15 20:00
How does one turn off automatic timezone?  Not seeing in Thunderbird -> Tools -> Options -> EWS tab.

**Comment by bavincen** [comment] 2015-06-15 20:21
lightning tab

**Comment by OfficeDrone6000** [comment] 2015-06-15 20:25
Timezone drop-down ("select the closest city in your timezone") is greyed out (and set to my correct time zone); I can't change it.  That's the only option re. timezone I see; it's in Tools -> Options -> Calendar -> General.  

Really sorry for the PEBKAC.

**Comment by poetimp** [comment] 2015-06-15 20:41
![tzone](https://cloud.githubusercontent.com/assets/3538244/8170234/1487d350-1364-11e5-8cd2-e1075ebdc26b.png)

Pasted image, hopefully this works....
Unclick the "Automatically change timezone" option

**Comment by OfficeDrone6000** [comment] 2015-06-15 20:48
I don't have an option for turning automatic time zone on or off, and no Timezone tab in Calendar options.  Here's a shot of my Calendar options:

![lightning_options](https://cloud.githubusercontent.com/assets/12899158/8170361/1fda833c-137e-11e5-9fc2-f3eaea3b9e42.png)

**Comment by poetimp** [comment] 2015-06-15 20:51
Versions ? :
Tbird: 31.7.0
Lightning: 3.3.3
Exchange EWS Provider: 3.4.0~beta2

**Comment by OfficeDrone6000** [comment] 2015-06-15 20:52
Windows 7, Thunderbird 38.0.1, Lightning 4.0.0.1, EWS 3.4.0b2

**Comment by poetimp** [comment] 2015-06-15 21:05
They may have removed the option on later releases that have not hit the Ubuntu repositories yet. Take a look at the advanced->config editor... It may or may not be there but you may be able to turn it off there if it does exist. I don't have the later versions so your YMMV

![image](https://cloud.githubusercontent.com/assets/3538244/8170642/17610530-1367-11e5-969b-84310642f6bc.png)

**Comment by OfficeDrone6000** [comment] 2015-06-15 21:19
Progress: that preference is not in the T'bird 38.0.1 options, so I added it manually and set it to false.

Restarted Thunderbird and the never-ending queued jobs problem appears to be gone.  Tested by modifying an existing calendar entry -- no queue stack-up as before with EWS 3.4.0b2.

**Comment by bavincen** [comment] 2015-06-16 04:43
We have temporarily disabled this. will keep working on from other side. thanks for help

**Closed by bavincen** 2015-06-16 04:43 UTC

**Comment by bavincen** [comment] 2015-06-16 04:46
https://github.com/Ericsson/exchangecalendar/commit/a949045ea07b06cdbdfac0f4894c35f338f59843

**Comment by raj45** [comment] 2015-06-17 09:09
I can confirm disabling "Automatically change timezone" fixes this problem.

**Comment by davidilieberman** [comment] 2016-08-10 14:31
Actually, setting the auto-timezone feature to false does not appear to help. My configuration is

Ubuntu 16.04
TB: 45.2.0
Lightning: 4.7
EWS Provider: 3.8.0

Source is Office365.

After upgrading EWS Provider, I immediately experienced the queued jobs problem. I deleted the calendar and recreated it, and the problem went away for a couple of days, but it appears to have resurfaced. I've been running with auto-timezone feature set to false for several days.

**Comment by bavincen** [comment] 2016-08-10 15:48
ah because we fixed cancelled items not deleted.
you might hv had many of them that were processed at once

**Comment by davidilieberman** [comment] 2016-08-10 16:23
Thanks, Babu, 

But in that case, wouldn't we expect to see a one-time hit? This seems to be happening pretty frequently. I just restarted tbird and am watching the queued jobs count climb to 1000+ and rising, with predictable impact on tbird's performance overall.

**Comment by oallart** [comment] 2016-10-12 02:08
Am experiencing the same issue as davidilieberman with the latest tbird/lightning/exchange as of writing. I have tried against multiple servers. auto-timezone off. It works then it stops working. 
I had a look in the calendar -> EWS settings -> Folder properties when the issue happens, and noticed that sometimes the whole tab is reporting no data at all (calendar is marked read-only as well)
Error console shows a syntax error with the https link to the server.

Here's a fix that has sometimes worked for me so far;
Look for the calendar that is hanging, right click, calendar -> EWS settings 
Retype the username (or delete/replace one letter) to force the 'check server and malibox' dialog to re-appear. Click it. save and reset.

Sometimes it works straight away, other times I need to change the server and or restart thunderbird.

Obviously a bug somewhere in the communication with the server ?

**Comment by davidmi** [comment] 2018-05-10 19:47
@oallart thank you that workaround worked for me!
