### ISSUE TITLE
Message Tagging still not working for other than English with latest master

### ISSUE THREAD

**Issue by markuskeunecke** [Ericsson/exchangecalendar#270] opened 2015-07-07 10:17 UTC
I cannot tag my mails in the inbox of an IMAP account on an exchange server. Neither via shortcut nor via mouse interface is working.

In issue #252 I uploaded a log and found the hint to latest master in #268 . I tried the latest master and it still is not working with that version.

I am on Ubuntu 14.04 using Thunderbird 38 with Lightning 4.0.0.1

I would suggest to make the tag sync deactivatable and turn it off by default.

Another side notice: 3.4.0~Beta3 had massive performance issues that did not occur anymore with latest master.

**Comment by bavincen** [comment] 2015-07-07 11:23
i think we should see your log... can you grepo ewsTagger and post.. Thanks .. 

also check the version of ews in addon page

**Comment by markuskeunecke** [comment] 2015-07-07 14:30
I need to revoke what I said about the performance issues having gone. They are still present...

As I said initially, I use the latest master from zip available as described in #268. It says 3.5.0~beta0.

Used log options:
export NSPR_LOG_MODULES="imap:5;lightning:5;calendar:5;timestamp"

Thunderbird log file excerpt is **empty** for grepping for ewsTagger:
http://pastebin.com/U0BBjGvb

Error console says related to exchange-calendar:

Timestamp: 07.07.2015 16:10:04
Warning: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
Source File: chrome://exchangecalendar/content/calendar-common-sets2.js
Line: 57, Column: 17
Source Code:
        function calendarCanModifyItems(aCalendar) { 
Timestamp: 07.07.2015 16:10:04
Warning: SyntaxError: in strict mode code, functions may be declared only at top level or immediately within another function
Source File: chrome://exchangecalendar/content/calendar-common-sets2.js
Line: 57, Column: 17
Source Code:
        function calendarCanModifyItems(aCalendar) {

If I did something wrong related

**Comment by bavincen** [comment] 2015-07-07 15:34
nope before that you have to enale logging...

https://github.com/Ericsson/exchangecalendar/wiki/Logging-Calendar-with-options

**Comment by markuskeunecke** [comment] 2015-07-07 15:37
Sorry for writing wrong. The pastebin has the information you wanted:
http://pastebin.com/U0BBjGvb

**Comment by bavincen** [comment] 2015-07-07 16:11
---: Initialized {1} - mail@domain.com
successfully running for the above a/c..

can you login in owa and check 
users having same setup like urs didnt complain so

**Comment by markuskeunecke** [comment] 2015-07-07 16:58
What should I check?

I logged in to OWA and did not see any tagged mails there, even not those being tagged before or automatically getting a tag.

**Comment by bavincen** [comment] 2015-07-08 02:54
Other ways to check . Right click on any mail go to tags on the menu you should see ewssync tags

**Comment by markuskeunecke** [comment] 2015-07-08 05:39
Yes, I see that entry in the context menu. But nothing more. Selecting it does not seem to have any effect

**Comment by bavincen** [comment] 2015-07-08 06:48
How do i reproduce please?

**Comment by markuskeunecke** [comment] 2015-07-08 06:55
Environment:
* Ubuntu 14.04
* Thunderbird 38 with 
  * Lighthning 4.0.0.1, 
  * EWS Provider 3.5.0-beta0, 
  * Provider for Google Calendar 1.0.4

Connect mail account via IMAP with an exchange server (the one I use is Exchange 2013). Try to tag E-Mails in account's inbox via shortcut, e.g. 1 for "important". Nothing happens for me. Using context menu of an E-Mail and selecting "Tags" -> "EWS Sync Tags" also has no visible effect. Neither of them creates visible changes in my inbox if I log into OWA of my exchange server.

**Comment by bberndt** [comment] 2015-07-10 21:48
I think this is a place to mention: happens to me too.  I haven't seen other problems, so far, or at least not noticed them. 

I DO HOWEVER, see that I cannot tag messages. Previously tagged are still tagged, and I haven't tried messing with them, but I cannot tag new messages.

I tried to revert back to the 3.3.0 release, but alas, it now doesn't work, I suspect, because Lightning has become to new for it.

Fedora 22, Cinnamon 2.6, Thunderbird 38.0.1

**Comment by bavincen** [comment] 2015-07-13 07:04
@bberndt please use latest add-on

**Comment by bavincen** [comment] 2015-07-13 07:04
Please check wiki

**Comment by laclaro** [comment] 2015-07-13 09:45
For me the commit "ewsTagger: Fix #268" did the trick: https://github.com/Ericsson/exchangecalendar/commit/002d93eced99001e52c3251b532a961c066db133#diff-e01fdf9a96a73ada2785b1659683feb6

Check your own file rtews.js for the changed lines in that commit, or just replace the whole content.
https://github.com/Ericsson/exchangecalendar/blob/002d93eced99001e52c3251b532a961c066db133/chrome/content/rtews.js

I did not try the master (just beta4 with the single changed file rtews.js), but suppose that it should be included there as well. Maybe something else breaks the functionality in latest-master again?

Best regards
Henning

**Comment by bberndt** [comment] 2015-07-13 16:16
getting 3.4 beta 4 from the wiki, and re-installing it made no difference. Is there a newer version that Im missing?

**Comment by bavincen** [comment] 2015-07-13 16:31
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

**Comment by ckoenig** [comment] 2015-07-14 12:29
I have the same problem. I cannot set any tags any more. I'm using the current master version as described in the wiki. After adjusting the log settings as mentioned in the thread I grepped for ewsTagger. The output can be found here: http://pastebin.com/nfB4Egfd

**Comment by nikoko** [comment] 2015-07-14 12:40
Same problem for me too: tag can not be used any more since the release of EWS
Im using Thundebird 38.1.0, Lightning 4.0.1 and EWS provider 3.4.0 beta1 on OSX 10.10.4

**Comment by bavincen** [comment] 2015-07-15 05:43
@nikoko beta1 on is buggy..  please use 
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

**Comment by bavincen** [comment] 2015-07-15 05:45
@ckoenig 
in ur log i can see your account is unauthorised

```javascript
1st-setup:2015-6-2 14:21:28.170:ewsTagger-----: Initialized {1} - mail@example.com
1st-setup:2015-6-2 14:21:31.560:ewsTagger-----: findFoldersError aCode:-19 aMsg: HTTP Client error 401: Unauthorized
```

**Comment by stelfrich** [comment] 2015-07-15 06:18
I experience the same problem on Ubuntu 12.04, Thunderbird 31.7.0, Lightning 3.3.7 with the latest EWS provider from master.

http://pastebin.com/jnHTEZWD

**Comment by ckoenig** [comment] 2015-07-15 06:37
@bavincen I don't really get that error message, since I receive mails and can see my calendar entries without any problems. Which authorization are we talking about here? Only tagging messages doesn't work any more, all the rest works as expected.

**Comment by bavincen** [comment] 2015-07-15 08:10
@stelfrich everything is fine.. i think need some more testing to report what bug is that.

**Comment by gwi2014** [comment] 2015-07-15 16:05
Does not work for me too. I can't create tags with Thunderbird 38.1.0, Lightning 4.0.1 and EWS provider 3.4.0 beta4. I enabled logging as described here https://github.com/Ericsson/exchangecalendar/wiki/Logging-Calendar-with-options. But there is no entry for ewsTagger in the log.

**Comment by bavincen** [comment] 2015-07-16 01:21
@gwi2014 beta is buggy.. please use
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

**Comment by bberndt** [comment] 2015-07-16 15:32
tagging still no worky with latest master. Jul-16.2015

**Comment by bavincen** [comment] 2015-07-16 16:38
@all tagging happens through calendar credentials. your email account not used for authenticating. if tagging work on remote you should have calendar configured

**Comment by bavincen** [comment] 2015-07-16 16:39
@laclaro  please test master

**Comment by ckoenig** [comment] 2015-07-17 08:14
After changing  [line 204 in rtews.js](https://github.com/Ericsson/exchangecalendar/blob/master/chrome/content/rtews.js#L204) from

    this.user = identity.domain +"\\"+identity.username ;

to

    this.user = identity.username ;

I got at least rid of the authentication error messages. So instead of '\mail@example.com' the user is now 'mail@example.com'. But tags are still not being synced between the client and the server.

**Comment by bavincen** [comment] 2015-07-17 08:55
Thanks @ckoenig 
Was that throwing any error . if yes please post the error.

**Comment by bavincen** [comment] 2015-07-17 09:09
@ckoenig Can you figure out where it is actually failing for you.. please
if you grep ewsTagger the log details everything nicely

**Comment by ckoenig** [comment] 2015-07-17 16:15
@bavincen I don't really see any errors within the [output of the log file](http://pastebin.com/3Z3ncyJD). But nonetheless the tags are not synchronized. Anything else I can provide to help investigate the problem?

**Comment by bavincen** [comment] 2015-07-17 16:19
@ckoenig 
1) let thunderbird sync
once complete mak any mail in owa wait for a log 
in next sync
you should see message update in local with numbers and message id




please check ur gloda is enabled or nor

**Comment by bavincen** [comment] 2015-07-17 16:20
Received update messages,  total items pending - 0
will be >1

**Comment by ckoenig** [comment] 2015-07-17 16:32
@bavincen Advanced / General / Advanced Configuration / Enable Global Search and Indexer is checked, so GLODA should be enabled. When I mark some message in OWA, the Thunderbird log contains the following:

```
1st-setup:2015-6-5 18:26:23.383:ewsTagger(mail@example.com): Received update messages,  total items pending - 1
1st-setup:2015-6-5 18:26:23.384:ewsTagger(mail@example.com): Received request to update messages,  total items to be requested - 1
1st-setup:2015-6-5 18:26:23.479:ewsTagger(mail@example.com): getItemsOK, Received server items to update: 1
1st-setup:2015-6-5 18:26:23.481:ewsTagger(mail@example.com): Server getItemsOK, received items:  1
1st-setup:2015-6-5 18:26:23.982:ewsTagger-----: Going to update server messages, total - 1
1st-setup:2015-6-5 18:26:23.985:ewsTagger-----: Going to update local messages, total - 0
1st-setup:2015-6-5 18:26:23.985:ewsTagger-----: Searching Gloda for messageId - b7095b2776f64b74a8b02fe09ee234cb@EXDAG03-2.EXCHANGE.INT in  folderPath - imap://mail%40example.com@example.com/posteingang
1st-setup:2015-6-5 18:26:23.985:ewsTagger-----: Gloda did not find message for messageId - b7095b2776f64b74a8b02fe09ee234cb@EXDAG03-2.EXCHANGE.INT in  folderPath - imap://mail%40example.com@example.com/posteingang
1st-setup:2015-6-5 18:26:38.306:ewsTagger(mail@example.com): Syncting TagItems now.
1st-setup:2015-6-5 18:26:38.404:ewsTagger(mail@example.com): Getting events finished..
```

**Comment by bavincen** [comment] 2015-07-17 16:46
great will fix it

**Comment by bavincen** [comment] 2015-07-21 13:17
Can someone try rebuilding goods index.. just thinking it may solve.

**Comment by ckoenig** [comment] 2015-07-21 15:27
I recreated the gloda index (at least I hope I did, I stopped Thunderbird, removed the file global-messages-db.sqlite in my profile directory, restarted Thunderbird and waited about 30 minutes), logged into OWA and marked a message. Unfortunately it's still the same errors: gloda cannot find the messages.

Anything else I can provide to help investigate the problem?

**Comment by bavincen** [comment] 2015-07-22 02:09
@ckoenig 
thanks.is that not removing .msf files.
i am not sure removing  db works// just asking sorry

**Comment by markuskeunecke** [comment] 2015-07-22 10:58
From Thunderbird Help: https://support.mozilla.org/en-US/kb/rebuilding-global-database

**Comment by ckoenig** [comment] 2015-07-22 11:59
Removing the .msf file doesn't help either.

**Comment by bavincen** [comment] 2015-07-23 13:44
Hmm ihave no idea why it works for me not you..

Some info for you guys..
Gloda actually stores message id which fetched from ews on the other side matched with gloda once mail found changes are applied.. there's nothing else

**Comment by ckoenig** [comment] 2015-07-23 15:54
OK, I finally had a look at the content of that sqlite DB. I can find those messageId in the messages table, but the referenced folder name is slightly different, e.g. instead of

    imap://mail%40example.com@exchange2013.example.com/posteingang

as mentioned in the Thunderbird log file, the name of the folder within the Gloda DB is

    imap://mail%40example.com@exchange2013.example.com/INBOX

I hope that helps you.

**Comment by bberndt** [comment] 2015-07-23 16:21
Is this thread talking about something other than what Im thinking?  

What my problem is, specifically, is:
Selecting a message in my inbox, going to the Tag menu, and selecting a Tag to apply to the message. (changing its color in the message list)  This functionality is broken with this add-on installed.  Works fine if I disable it.

Indeed I do get my mail from an Exchange server, and of course use this add-on for the access to calendars on said Exchange server. 

However, my mail is received via POP, so after it gets here, has nothing to do with said exchange server.

**Comment by markuskeunecke** [comment] 2015-07-23 16:25
@bberndt That is exact my problem apart from me using an IMAP connection to the exchange server.

**Comment by bavincen** [comment] 2015-07-23 18:08
@ckoenig  i agree that could be a problem

**Comment by bavincen** [comment] 2015-07-23 18:09
@bberndt we will exclude pop

**Comment by bavincen** [comment] 2015-07-28 05:43
Please update the bug status

https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

**Comment by markuskeunecke** [comment] 2015-07-28 08:03
Thank you. With current master tagging is working and can be turned off.

**Comment by bavincen** [comment] 2015-07-28 08:24
Great! remote tagging is working for you?

**Comment by markuskeunecke** [comment] 2015-07-28 08:28
I have observed that if I flag a message in OWA it gets starred in thunderbird. If I tag a mail in thunderbird, the tag is not synchronized to OWA (this might be by intent?)

**Comment by bavincen** [comment] 2015-07-28 08:30
yes. we have added a option to enable mail properties syncing. please go to ews settings change your option for mail syncing under mail settings tab

**Comment by bavincen** [comment] 2015-07-28 08:31
if thats not happening(remote) at all..
grep ewsTagger
tag one mail in owa 

wait for the sync in TB
post that sync log..

**Comment by stelfrich** [comment] 2015-07-28 08:38
With the current build from master, no tags are showing up in the Tag context menu. Hence, I can't really execute the previously mentioned tasks. Grepping the logfile in my case only returns:

```1st-setup:2015-6-2 10:35:27.45:ewsTagger-----: Account exists  for email address - mail1@domain.com```
```1st-setup:2015-6-2 10:35:27.45:ewsTagger-----: Account exists  for email address -  mail2@domain.com```

**Comment by markuskeunecke** [comment] 2015-07-28 09:55
Okay, I did some more testing and noticed a few things.

* Tagging only works for me if it is deactivated. It produces log entries but has no effect neither in TB nor in OWA
* Enabling/disabling tagging needs a restart of TB.
* Starring messages in TB leads to flagged messages in OWA. (Seems to be default IMAP behaviour?)
*  I cannot tag mails in my OWA version (iirc it is version 2013 or maybe 2010). I can only set follow up flags there.

I uploaded the log to pastebin: http://pastebin.com/mVTdTSnH

**Comment by bavincen** [comment] 2015-07-28 10:41
can you take that latest on master and check again @stelfrich

**Comment by bavincen** [comment] 2015-07-28 10:43
@markuskeunecke please take latest master.
1) please use owa to set tag  after Thunderbird is started  
* don’t tag from Thunderbird
and check that log in Thunderbird 
immediately tagging in owa

**Comment by bavincen** [comment] 2015-07-28 10:43
@markuskeunecke your log looks good what ever you have posted

**Comment by bavincen** [comment] 2015-07-28 10:44
@stelfrich  you dont have calendar configured for mail account . if yes you have to enable mailsyncing in ews settings

**Comment by stelfrich** [comment] 2015-07-28 10:59
@bavincen I can tag locally, with the latest master. The tags are, however, not synced with the Exchange server (checked via OWA and Outlook) in either direction.

I have the calendars configured and the syncing is activated. The delay (whatever that means?) is set to 15.

**Comment by bavincen** [comment] 2015-07-28 11:04
https://github.com/Ericsson/exchangecalendar/wiki/EWS-Mail-Settings

please post me ewstagger log @stelfrich

**Comment by bavincen** [comment] 2015-07-28 11:13
what is your sea-monkey or Thunderbird language? please

**Comment by markuskeunecke** [comment] 2015-07-28 11:27
First: I just installed latest master and observed the behaviour with this version.

Okay, I use OWA only as fallback if I do not have access to my computer with TB. I tried what you said in OWA, but I cannot find a way to tag my e-mails. The only thing I can do there is to mark a mail for follow up which leads to starring a message in my TB. Setting other tags is not possible for me, sorry. :)

Anyway as you propose to only set tags from OWA, which does not fit to my workflow, I am completely happy with having the possibility to switch off tag synching. :)

I think we have a big misunderstanding here: I thought, that synchronizing tags meant two ways, from TB to OWA and back. But as it seems to me now, you implemented only the direction OWA --> TB for the moment.

My log extract shows tagging mails in TB. One with the feature enabled in EWS and one with it being disabled. Having the feature enabled had no effect in OWA and in TB. After a restart no tagging was posssible anymore.

**Comment by bavincen** [comment] 2015-07-28 13:38
Okay for your clarification. It's not one way.. the reason why I told to you to mark it in owa is to check what's is happening on the sync.

You are unable to do remote tagging from tb also

So logging will help others. You can keep them disabled btw

**Comment by bavincen** [comment] 2015-07-28 13:40
To tag email you can check a box just left to flag

**Comment by bavincen** [comment] 2015-07-28 13:43
If remote tagging doesn work it may be because of language . It's working for english US

**Comment by markuskeunecke** [comment] 2015-07-28 13:43
Okay, then I got it wrong. :) But yes, I am unable to do so from both sides. Maybe this is the root cause of my problem. :) Maybe you can check exchange's capabilities and disable feature based on EWS interface . :)

Anyway: having it disabled is okay for me.

**Comment by ckoenig** [comment] 2015-07-28 15:32
Just a short update. The tag syncing still doesn't work for me (as before the wrong folder name is used, i.e. posteingang instead of INBOX). As you mentioned the problem seems to be the German Exchange server. But since I can disable that feature now easily, I can tag my messages in Thunderbird again.

**Comment by bberndt** [comment] 2015-07-28 18:28
I can tag a message again! with latest build downloaded July 28.
Thunderbird 38.1.0
Lightning 4.0.1.2
Fedora 22
Cinnamon 2.6.5
Exchange 2010, using POP3 for incoming mail.

**Comment by bavincen** [comment] 2015-08-03 05:44
```javascript
                        for (var j = 0; j < aCollection.items.length; j++) {
                            if (aCollection.items[j].folder.uri.toLowerCase().endsWith(folderPath.toLowerCase())) {
                                if (aCollection.items[j].folderMessage != null) {
                                    msgHdrs.push(aCollection.items[j].folderMessage);
                                }
                            }
                        }
```
this is checking if the folder uri is matching with message in gloda.
this part can not be skipped as it checking right folder the message IN.

any idea?

FYI
https://github.com/Ericsson/exchangecalendar/blob/924ad8bc12330133fa933b09c1c122aeeef5fce0/chrome/content/rtews.js

**Comment by jakob1** [comment] 2015-08-12 08:39
Sorry, it doesn't work for me. I have to disable Exchange EWS Provider 3.4.0 beta 5, to tag (local) messages.

Thunderbird 38.1.0 German
Lightning 4.0.1.2
Exchange EWS Provider 3.4.0 beta 5
Win7

**Comment by bavincen** [comment] 2015-08-12 10:12
Please use latest add on.

Please refer wiki for installation details 

Sent from my Sprint phone.

----- Reply message -----

**Comment by jakob1** [comment] 2015-08-12 10:25
Hello,
thank you for your reply, but as I wrote I already use
Exchange EWS Provider 3.4.0 beta 5

Nevertheless I reinstalled it, but it it doesn't work
Sorry

best regards
Jakob


Am 12.08.2015 um 12:12 schrieb bavincen:

**Comment by kdg1** [comment] 2015-08-12 13:36
I, also, have not been able to tag emails in my primary Account since the LIghtning 4 release. I have been monitoring this thread for a month, trying each new release. I am using the current release 3.5.0 beta 0.
My primary account is a pop server, the tags visbile via the dropdown but nothing happens when they are assigned.
I have another pop account, an imap account, and local folders and tagging does work with each of these. I also have an exchange account which has rules to tag new mail in the inbox mail and move it to my primary account, which works, it tags them and moves them and I see these tags in my primary account.
But I cannot tag emails in my primary pop account. I can see the available tags in the tag dropdown and I can remove pre-existing tags by using the 'remove all tags' option but not by un-selecting the actual tag currently assigned.
Very frustrating, please help.

**Comment by bavincen** [comment] 2015-08-13 08:21
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

@jakob1  please use this...

**Comment by bavincen** [comment] 2015-08-13 08:23
Please tell us about your thunderbird, lightning versions .

**Comment by kdg1** [comment] 2015-08-13 09:48
Thunderbird 38.1.0
Lightning 4.0.1.2
Exchange EWS Provider 3.5.0-beta0
If I disable Exchange EWS Provider, then tagging in the primary folder works well.

**Comment by jakob1** [comment] 2015-08-13 09:51
@bavincen Thank you very much for your latest suggestion getting Exchange EWS Provider 3.5.0-beta 0. Tagging exchange mails works now for me.

**Comment by bavincen** [comment] 2015-08-13 16:12
closing it thanks all

**Closed by bavincen** 2015-08-13 16:12 UTC
Labels: fixed, please test, resolved

**Comment by kdg1** [comment] 2015-08-13 16:32
@bavincen What about my issue of not being able apply tags?

**Comment by bavincen** [comment] 2015-08-14 01:08
please open new issue with ur log.
