### ISSUE TITLE
Cannot tag e-mails if the extension is enabled

### ISSUE THREAD

**Issue by sliwowitz** [Ericsson/exchangecalendar#252] opened 2015-06-21 21:03 UTC
In Thunderbird 38.0.1 with Exchange Calendar 3.4.0-beta3, tagging emails doesn't work. If I right-click the email, numpad keys don't tag the mails, and there are no tags available listed in the menu (although they do appear in the list brought up using the "manage tags" menu item).

**Comment by laclaro** [comment] 2015-06-22 09:29
This is also a duplicate of https://github.com/Ericsson/exchangecalendar/issues/208

Best regards,
Henning

**Comment by bavincen** [comment] 2015-06-22 09:58
Hi would you mind giving a try 

https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

the troubles are due to supporting  latest sea monkey ,Thunderbird and  lightning..

**Comment by sliwowitz** [comment] 2015-06-22 11:21
Even the latest master has the problem in TB 38. (but in TB 37, it works fine)

**Comment by bavincen** [comment] 2015-06-22 11:22
We need your lightning version please.. thanks

**Comment by sliwowitz** [comment] 2015-06-22 15:19
Sorry. For whatever reason, the lightning plugin just disappeared from my TB 38 installation (I have no idea how it happened, I was using the calendar last friday, so I didn't suspect it wouldn't be there until I went to check the verion). When I noticed the problem, I had exchange calendar plugin installed, but no lightning. After installing lightning, the problem went away.

To trigger the bug, you have to enable exchange calendar and disable lightning. Even though this extension interfering with email tagging feels like a bug, I can hardly imagine a real-life scenario where that would be a problem, so you can probably close this bug.

Cheers, and thanks for the work you do,
Jiri

**Comment by laclaro** [comment] 2015-06-23 07:51
I have lightning 3.3.3. in Thunderbird 31.7.0, both plugin and lightning enabled. Problem persists. I am able to remove tags from e-mails but not to add new ones.

sliwowitz, are you saying this problem is not present for the most recent Thunderbird 38.0.1 and Lightning 4.0.0.1?

Best regards,
Henning

**Comment by sliwowitz** [comment] 2015-06-23 10:25
Interesting. For me, it now works on both of my computers - one is TB 38.0.1 + Lightning 4.0.0.1 + latest (4b57da5fec) exchange calendar master. The other is TB 31.7.0 + Lightning 3.3.3 + exchange calendar 3.4.0-beta3.

The TB 31.7 combo didn't have this problem at all, in TB 38 the problem disappeared when I reinstalled Lightning from the update site.

I cannot reproduce the bug now.

**Comment by Dominique-2202** [comment] 2015-06-23 11:13
The bug is still there with SeaMonkey (no message tagging possible)

**Comment by bavincen** [comment] 2015-06-23 12:13
https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon

Can you guys check the latest.. 

@Dominique-2202 Enable logging;;  grep -i  ewsTagger , so we can see what is missing

**Comment by bavincen** [comment] 2015-06-23 12:19
@Dominique-2202 lighning 35b1 seamonkey 2.3

**Comment by Dominique-2202** [comment] 2015-06-23 12:47
Hello Bavincen,
        
        Thanks a lot for your hard work and dedication.
        
        This new version is now working for me (release SeaMonkey and
        Lightning, Google Provider too...). Regular message tagging now
        works and there is no hit in the logs for ewsTagger !
        
        hope this helps.
        
        Note: this version is still referenced as "beta 1" and asks for
        the upgrade to Beta 3 !! Maybe a beta 4 coming soon ?
      
    
      
      
      
        Best regards,
        
        Dominique 
        
       
    On 6/23/2015 2:19 PM, bavincen wrote:
    
    
      @Dominique-2202
        lighning 35b1 seamonkey 2.3
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by bavincen** [comment] 2015-06-23 15:21
version is not changed in master..
 we will release it soon.. we are behind couple of issues.


p.s please confirm that on related tag issue opened..

**Comment by Dominique-2202** [comment] 2015-06-23 15:28
Hi Bavincen,
        
        Confirming to solve the issue of message tagging !
        
        SeaMonkey and lightning "release" versions, EWS version from
        master.zip on Github.
      
    
      
      
      
        Best regards,
        
        Dominique 
        
       
    On 6/23/2015 5:21 PM, bavincen wrote:
    
    
      version is not changed in master..
        we will release it soon.. we are behind couple of issues.
      p.s please confirm that on related tag issue opened..
      —
        Reply to this email directly or view
          it on GitHub.

**Closed** 2015-06-24 05:43 UTC
Labels: notabug, wontfix, worksforme

**Comment by laclaro** [comment] 2015-06-29 07:30
Hello,

Dominique, would you tell me how you got event tagging running? I need this feature. I already tried deleting cache files, disabling all other addons and starting a new clean TB 38.0.1/lightning 4.0.0.1 profile from scratch with only lightning and exchangecalendar installed. Tried this with severa different versions of the plugin including latest and most recent release.

I would therefore say, that this still needs to be fixed.

Best regards,
Henning

**Comment by markuskeunecke** [comment] 2015-06-29 10:01
Using Thunderbird 38, Lightning 4.0.0.1 together with beta4 still has the issue where I cannot manually tag mails.

**Comment by bavincen** [comment] 2015-06-29 10:54
@markuskeunecke  can you provide us your log.. you can grep "ewsTagger"

**Comment by markuskeunecke** [comment] 2015-06-29 11:15
I cannot attach log files here out of the box. I had to rename them first.

![exchangecalendar](https://cloud.githubusercontent.com/assets/3355613/8406840/cc0206f2-1e60-11e5-8c5f-bbd59659870e.png)
![thunderbird](https://cloud.githubusercontent.com/assets/3355613/8406841/ce30762a-1e60-11e5-89f1-c36f32d36339.png)

**Comment by markuskeunecke** [comment] 2015-06-29 12:52
Using beta3 in my setup does not have the bug.

**Comment by bavincen** [comment] 2015-06-29 12:54
Please use beta 4 always advised to stay with recent version
Thanks

**Comment by markuskeunecke** [comment] 2015-06-29 13:13
Sure, I'd love to do that. But for me it is broken, as I make massive use of the mail tagging feature. Losing this feature is a blocker for me. Hopefully you can analyze with my information on the feature working in beta3 and not in beta4 where the bug has its origin. :) As soon as you release a new version I will be willing to test. :)

**Comment by bavincen** [comment] 2015-06-29 13:25
@markuskeunecke obj I got it wrong. Will check

**Comment by laclaro** [comment] 2015-06-29 15:42
This may be relevant:

```
1st-setup:2015-5-1 17:39:22.556:[contacts] exchangeAbRootDirectory: cardForEmailAddress (_cardForEmailAddress in exchangeAbRootDirectory.js:246)
1st-setup:2015-5-1 17:39:35.10:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({69150b77-b561-43a2-bfba-7301dd5a35d0})
1st-setup:2015-5-1 17:39:35.13:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({f6a0d1e5-369f-4abc-81ae-d370d36e4006})
1st-setup:2015-5-1 17:39:35.15:  >>>>>>>>>>> MAIL THIS LINE TO exchangecalendar@extensions.1st-setup.nl: ecnsIAuthPrompt2.getInterface({0d6ce59c-ad5d-4520-b4d3-09664868f279})
1st-setup:2015-5-1 17:39:35.36:[RWTH Calendar] setProperty. aName:exchangeCurrentStatus, aValue:0 (setProperty in mivExchangeCalendar.js:828)
1st-setup:2015-5-1 17:39:35.37:[RWTH Shared] setProperty. aName:exchangeCurrentStatus, aValue:0 (setProperty in mivExchangeCalendar.js:828)
```

This popped up on hitting a key to tag a selected message. No messages on manually selecting "Sync EWS Tags" from the menu.

Best regards,
Henning

**Comment by bavincen** [comment] 2015-06-29 16:03
\\\ @laclaro are you using beta 4. this is working fine

**Comment by laclaro** [comment] 2015-06-30 15:42
I am on that very version. However, I cannot tag messages. :( I go on in bug https://github.com/Ericsson/exchangecalendar/issues/268

**Comment by JessHolle** [comment] 2016-01-11 12:26
Hmmm....  This is not working for me with TB 38.5.1 and supposedly the latest EWS and Lightning (at least check for updates doesn't bring me any updates).

**Comment by bavincen** [comment] 2016-01-12 13:34
It needs a fix. May be due to latest lightning upgrade. If anyone like to
fix kindly check chrome/content/rtews.js

**Comment by JessHolle** [comment] 2016-01-12 14:06
This actually turned out to be use of an old version of EWS.  The 
check-for-update wasn't finding the new version.  I checked the web 
site, found the new version, manually downloaded and installed it, and 
the issue went away.

**Comment by bavincen** [comment] 2016-01-12 14:07
Oh that's great
