### ISSUE TITLE
exchangecalendar fails to connect to server after Thunderbird restart when password is stored in password manager

### ISSUE THREAD

**Issue by maciejjo** [Ericsson/exchangecalendar#103] opened 2015-02-11 11:54 UTC
Hi,

I have a strange issue with exchangecalendar, when I set up calendar it works fine, when I close Thunderbird and start it again, no items from calendar show up (this doesn't happen always, but if I restart after more than 5 minutes it is almost certain). From log I see that I got 401 Unauthorized:

	1st-setup:2015-1-3 12:34:13.23:mivExchangeAuthPrompt2: passwordManagerGet found password for: username=intra\msobkows, aURL=https://webmail.intra.net/EWS/Exchange.asmx, aRealm=Exchange Web Service (_passwordManagerGet in mivExchangeAuthPrompt2.js:622)
	1st-setup:2015-1-3 12:34:13.23:mivExchangeAuthPrompt2: getPassword: There is a password stored in the passwordManager. (_getPassword in mivExchangeAuthPrompt2.js:153)
	1st-setup:2015-1-3 12:34:13.23:mivExchangeAuthPrompt2: getPassword: password(2)=******** (_getPassword in mivExchangeAuthPrompt2.js:164)
	1st-setup:2015-1-3 12:34:13.23:mivExchangeAuthPrompt2: asyncPromptAuthNotifyCallback: getPassword exception. err:URIError: malformed URI sequence (_asyncPromptAuthNotifyCallback in mivExchangeAuthPrompt2.js:338)
	1st-setup:2015-1-3 12:34:13.24:0d958714-5ebc-432d-b440-9fe6f668729d: : ExchangeRequest.onLoad :load, readyState:4, status:401
	1st-setup:2015-1-3 12:34:13.24:0d958714-5ebc-432d-b440-9fe6f668729d: : ExchangeRequest.onLoad :Server: Microsoft-IIS/7.5
	WWW-Authenticate: Negotiate
	NTLM
	X-Powered-By: ASP.NET
	Date: Wed, 11 Feb 2015 11:36:32 GMT
	Content-Length: 0

	1st-setup:2015-1-3 12:34:13.24:0d958714-5ebc-432d-b440-9fe6f668729d: : ExchangeRequest.onLoad :
	1st-setup:2015-1-3 12:34:13.24:0d958714-5ebc-432d-b440-9fe6f668729d: exchangeRequest.isHTTPRedirect.xmlReq. xmlReq.readyState:4, xmlReq.status:401
	1st-setup:2015-1-3 12:34:13.24:0d958714-5ebc-432d-b440-9fe6f668729d: : isConnError req.status=401: Unauthorized
	URL:https://webmail.intra.net/EWS/Exchange.asmx

	1st-setup:2015-1-3 12:34:13.24:0d958714-5ebc-432d-b440-9fe6f668729d: ecExchangeRequest.fail: aCode:-19, aMsg:HTTP Client error 401: Unauthorized
	URL:https://webmail.intra.net/EWS/Exchange.asmx

	1st-setup:2015-1-3 12:34:13.25:[exchangeLoadBalancer] fb47d353-1a53-43be-9eed-e72500598cdb:https://webmail.intra.net/EWS/Exchange.asmx:jobObject:onRequestError. arg2:-19, arg3:HTTP Client error 401: Unauthorized
	URL:https://webmail.intra.net/EWS/Exchange.asmx

	 (_onRequestError in mivExchangeLoadBalancer.js:86)
	1st-setup:2015-1-3 12:34:13.25:[My calendar] checkFolderPathError: Code:-19, Msg:HTTP Client error 401: Unauthorized
	URL:https://webmail.intra.net/EWS/Exchange.asmx

Then when I delete this calendar and re-add it, sometimes it succeeds, sometimes I get error as well. We have two servers, sometimes changing server helps. In general, everything is pretty much random. Recently I did a clean OS install, and in previous install I had the same setup, I don't remember anything like that. (This was about two months ago). 

EDIT:
It looks like it helps to delete the password from manager and set up the calendar again. When I enter the password manually, it seems to work. But when I enable plaintext password login, it prints it and it matches.

Ok, now I am certain - this only happens with password stored in password manager. Adding calendar didn't work randomly, but only when I cleared saved passwords first. The same goes for restarting - when I add calendar, it accepted password and synchronized, but when I restarted it took password from manager and failed. But, as I said, when logging password was enabled, it printed correct password to log.

Versions:
Thunderbird 31.4.0
Exchange EWS Provider 3.3.0 (I tried newest release as well, same issues)
Lightning 3.3.3

**Comment by pdunbar-methods** [comment] 2015-02-24 17:54
I've experienced this issue for quite some time.  My work-around has been to set my thunderbird homepage to <https://{myhost}/ews/exchange.asmx>.  At thunderbird start, this begins an authenticated https session with ews, and things work fine from there.  Usually, the home page doesn't come up so I have to hit alt+home in order to get the login prompt.  But this all only happens once per session for me.

**Comment by bavincen** [comment] 2015-02-25 03:55
Hi
I think this issue is not very clear.
What I see is server is negotiating  your login.
Negotiating simply means your username or password is not correct

**Comment by maciejjo** [comment] 2015-03-05 18:26
Ok, in theory you are right, but it is correct. When I turned password visibility on I could clearly see and confirm that it was correct. If I wasn't sure, I wouldn't post this issue. I tried multiple times, and it only works when password is not saved.

**Comment by CRCinAU** [comment] 2015-03-08 00:15
Ok, so I was pulling my hair out when I couldn't get this thing to connect after having a successful connection a couple of times.... It didn't matter what I did, I always got *Unauthorised 401* back... Deleting and readding the calendar didn't work. After removing the password manager entry - bingo - it worked perfectly again.

As soon as a told Thunderbird to remember the password again, boom, it was broken.

This is using 3.3.1 ~RC4.

**Comment by CRCinAU** [comment] 2015-03-08 03:17
I should also note that I use the ExQuilla plugin as well to do mail from EWS in thunderbird. if *either* plugin saves the password, then this will fail.

**Comment by muthusuba** [comment] 2015-03-08 06:29
@maciejjo @CRCinAU Thank you for debugging+confirming!

**Comment by Mechtilde** [comment] 2015-03-08 07:19
Hello,


Am 08.03.2015 um 04:17 schrieb CRCinAU:
> I should also note that I use the ExQuilla plugin as well to do mail
> from EWS in thunderbird. if *either* plugin saves the password, then
> this will fail.

Which function do you miss in Thunderbird to mail from EWS. Why do you
use ExQuilla?

We can discuss this beside this thread.

Kind regarrds
-- 

Mechtilde Stehmann
## Key-ID 0x141AAD7F

**Comment by CRCinAU** [comment] 2015-03-08 07:23
I use ExQuilla purely for mail access via EWS.

**Comment by Mechtilde** [comment] 2015-03-08 07:52
Am 08.03.2015 um 08:23 schrieb CRCinAU:
> I use ExQuilla purely for mail access via EWS.

I have no problems to do it without this AddOn which isn't Free Software
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Ericsson/exchangecalendar/issues/103#issuecomment-77736951
> 

-- 
Mechtilde Stehmann
## PGP encryption welcome
## Key-ID 0x141AAD7F

**Comment by CRCinAU** [comment] 2015-03-08 07:53
Interesting - maybe email me direct - netwiz@crc.id.au and we'll talk (without polluting this report more)

**Comment by bavincen** [comment] 2015-03-08 08:12
Duplicate of #42

We found this issue.. 

Thanks

**Closed** 2015-03-08 08:12 UTC
Labels: bug
