### ISSUE TITLE
Accepting Event does not work anymore in v3.9.0-beta1

### ISSUE THREAD

**Issue by nudgegoonies** [Ericsson/exchangecalendar#549] opened 2016-12-16 08:05 UTC
When i receive an event and click on accept a window appears where i have the choice to answer, answer with text and not answer at all. I can still click on one of the options but after that the window pops up again. The only chance to close the window is to change to the main Icedove (Thunderbird name in Debian) window and quit Icedove at all.

I hope this is understandable. I use the german version of Icedove and Iceowl (Lightning name in Debian). My operating system is Debian 8 with Icedove 45.5.1, Iceowl 4.7.5.1.

This bug is not present in version 3.8.0 of the plugin so i reverted to this version at the moment.

**Comment by afettouhi** [comment] 2016-12-21 07:08
I can confirm that as well. I'm on Arch Linux 64 bit with Thunderbird 45.5.1.

**Comment by kpocius** [comment] 2016-12-27 22:12
This is a duplicate of #542. Let's keep them consolidated and not post additional comments here.

**Comment by bavincen** [comment] 2016-12-29 05:06
can you try beta2 please

**Comment by afettouhi** [comment] 2016-12-29 06:41
Running beta 2 right now and the issue is still there.

**Comment by nudgegoonies** [comment] 2017-01-03 09:01
Is this really the fix?
https://github.com/Ericsson/exchangecalendar/compare/Ericsson:v3.9-beta1...v3.9.0-beta2

**Comment by dmnrmr** [comment] 2017-01-03 11:12
I get these errors when I try to accept invite (3.9.0-beta2):

```
Timestamp: 01/03/2017 01:10:05 PM
Error: TypeError: proposeStart.getInTimezone is not a function
```

And I get this error 3 times:
```
Timestamp: 01/03/2017 01:10:05 PM
Error: NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: JavaScript Error: "proposeStart.getInTimezone is not a function"
```

[log.txt](https://github.com/Ericsson/exchangecalendar/files/682105/log.txt)

**Comment by valerioa** [comment] 2017-01-05 23:23
A fix that works for me (3.9.0-beta2) is changing the two lines, in 
```
<thunderbird user profile folder>/extensions/<extension folder>/interfaces/exchangeCalendar/mivExchangeCalendar.js
```

```
---
input.proposeStart = cal.toRFC3339(proposeStart.getInTimezone(this.globalFunctions.ecUTC()));
input.proposeEnd   = cal.toRFC3339(proposeEnd.getInTimezone(  this.globalFunctions.ecUTC()));
---
```

to

```
---
if ( proposeStart )
{ input.proposeStart = cal.toRFC3339(proposeStart.getInTimezone(this.globalFunctions.ecUTC())); }
if ( proposeEnd )
{ input.proposeEnd   = cal.toRFC3339(proposeEnd.getInTimezone(  this.globalFunctions.ecUTC()));  }
---
```
then restart Thunderbird.

Most of the invites I receive have proposeStart and proposeEnd undefined

**Comment by oaxjogi** [comment] 2017-01-06 09:18
I can confirm on Windows 10 Prof + Thunderbird 45.6.0 + v3.9.0-beta2 that the fix works for me.

**Comment by gpreitsma** [comment] 2017-01-09 02:27
Same here. After making the change proposed by valerioa, I can accept invites again :).

Windows 7 Prof + Thunderbird 45.6.0 + v3.9.0-beta2

**Comment by afettouhi** [comment] 2017-01-09 20:11
Proposed fix works for me as well on Arch Linux with Thunderbird 45.6.0 and v3.9.0-beta2.

**Comment by nudgegoonies** [comment] 2017-01-10 09:06
The fix also works for me with Debian 8, Icedove 45.5.1, and v3.9.0-beta2 with the fix above.

**Comment by cseader** [comment] 2017-01-10 18:43
This did not fix me.
I have the following:
EWS Provider 3.9.0 Beta 2
Lightning 4.7.6
Thunderbird 45.6.0
OS: Tumbleweed 

It would be nice to know what version of Lightning is supposed to work with everything. There is no mention of this in any docs. Since Lightning now comes with Thunderbird its assumed that the latest EWS provider works with it, but its not always the case.

**Comment by valerioa** [comment] 2017-01-11 13:59
@cseader , the fix should be working for you too, as I'm on Mac OSX Sierra, Thunderbird 45.6.0,  and v3.9.0-beta2 . Others, for whom the fix works, are on Windows and Linux, so it is a fix architecture-independent . One can have multiple Thunderbird profiles in one's directory, and have multiple EWS extension folders in a profile, if you have installed EWS multiple times. Suggest make sure you're editing the js file in the active profile and in the active extension folder.

**Closed as completed** 2017-01-14 10:30 UTC
