### ISSUE TITLE
Can't accept invitation to meetings

### ISSUE THREAD

**Issue by trourance** [Ericsson/exchangecalendar#579] opened 2017-03-29 14:49 UTC
Hi, I'm using the latest 3.9.0 version. 
I can't confirm my participation to meetings anymore without sending a reply.
I'm forced to edit the answer before sending it, or it's not sent at all and the status keeps in temporary.
But even when I do that, the meeting appears in the calendar, but the invitations stays in my email as if I had not answered.

**Comment by tjbwyk** [comment] 2017-04-04 13:09
The same..

**Comment by jdkloe** [comment] 2017-04-07 08:18
confirmed on my side as well.

**Comment by kstripp** [comment] 2017-04-12 17:19
Seems to be the same behavior that I started getting this week after our IT did a "service update".  (They of course didn't specify anything more detailed than that)

Might be duplicate of #542

**Comment by jdbarnesusc** [comment] 2017-04-12 20:00
same problem here. what logs/files can we attach to this to help? it is the worst with multiple meeting requests.

**Closed as not planned** 2024-08-13 15:21 UTC
