### ISSUE TITLE
Cannot add calendar

### ISSUE THREAD

**Issue by NeilHanlon** [Ericsson/exchangecalendar#84] opened 2015-01-28 19:43 UTC
Heyo everyone,

I'm trying to add a calendar on a hosted Office365 Exchange server. I'm using Postbox with their custom Lightning plugin (unsure of what version it's forked from), and the latest version of ExchangeCalendar which I modified to install inside of Postbox (needed the min/max version stuff).

When I go to add a calendar, I click "Check Server and Mailbox" and it just sits there. In the log, I see this:

```
1st-setup:2015-0-3 14:39:56.468:exchWebServicesConvertIDOK: user:wit.edu\hanlonn@wit.edu, mailbox:hanlonn@wit.edu
```

The EWS URL i'm using is:

https://outlook.office365.com/EWS/Exchange.amsx

Screenshot: https://labs.neilhanlon.com/ss/2015-01-28_1443.png

Is this a known issue? Are there debugging steps I can take?

**Comment by Dominique-2202** [comment] 2015-01-29 07:37
Just a suggestion: you seen in the screenshot here to put your domain and user name in the same line. Could you try with the domain and user, each in its own line ? (guessing that wit.edu is the domain here...).

**Comment by NeilHanlon** [comment] 2015-01-29 14:45
I've tried it that way, as well as a lot of other ways, unfortunately.

**Comment by NeilHanlon** [comment] 2015-02-04 14:34
Anyone else have any thoughts?

**Comment by Dominique-2202** [comment] 2015-02-04 14:38
no real thought...Just wondering if Postbox and its " custom"  lightning might be the cause. IT could be worth trying with standard Thunderbird + Lightning, to see if it works.

**Comment by bararchy** [comment] 2015-02-04 14:40
I'm using those configurations with office365:
Server URL: ```https://outlook.office365.com/EWS/Exchange.asmx```
User name and Primary email address are the same, a full email address 
Domain name: (this is empty)

**Comment by muthusuba** [comment] 2015-03-13 06:39
@NeilHanlon Is this working for you, please? I'm closing it for now...please reopen it if its still not working...

@Dominique-2202 @bararchy Thanks a lot for helping out!

**Closed by muthusuba** 2015-03-13 06:39 UTC
